import java.io.File;
import java.io.PrintWriter;

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;

public class RecoverNative extends GhidraScript {
    private boolean isTargetFunction(String functionName) {
        return functionName.startsWith("YYGameMemory") ||
            functionName.startsWith("YYUnity") ||
            functionName.startsWith("YYIslandRoute") ||
            functionName.equals("RussIslandRouteOverlaySetEnabled") ||
            functionName.equals("RussIslandRouteOverlayShutdown");
    }

    @Override
    public void run() throws Exception {
        String[] arguments = getScriptArgs();
        if (arguments.length != 1) {
            throw new IllegalArgumentException("Expected output file path");
        }

        File outputFile = new File(arguments[0]);
        File parentDirectory = outputFile.getParentFile();
        if (parentDirectory != null && !parentDirectory.exists() && !parentDirectory.mkdirs()) {
            throw new IllegalStateException("Unable to create output directory");
        }

        DecompInterface decompiler = new DecompInterface();
        decompiler.setSimplificationStyle("decompile");
        if (!decompiler.openProgram(currentProgram)) {
            throw new IllegalStateException("Unable to open program for decompilation");
        }

        int recoveredCount = 0;
        try (PrintWriter writer = new PrintWriter(outputFile, "UTF-8")) {
            writer.println("/* Generated by Ghidra from RussOriginal.dylib. */");
            FunctionIterator functions = currentProgram.getFunctionManager().getFunctions(true);
            while (functions.hasNext() && !monitor.isCancelled()) {
                Function function = functions.next();
                String functionName = function.getName();
                if (!isTargetFunction(functionName)) {
                    continue;
                }

                DecompileResults result = decompiler.decompileFunction(function, 120, monitor);
                if (!result.decompileCompleted() || result.getDecompiledFunction() == null) {
                    writer.printf("/* Unable to decompile %s at %s */%n%n", functionName, function.getEntryPoint());
                    continue;
                }

                writer.printf("/* %s at %s */%n", functionName, function.getEntryPoint());
                writer.println(result.getDecompiledFunction().getC());
                writer.println();
                recoveredCount++;
            }
            writer.printf("/* Recovered functions: %d */%n", recoveredCount);
        } finally {
            decompiler.dispose();
        }

        if (recoveredCount == 0) {
            throw new IllegalStateException("No named target functions were recovered");
        }
    }
}
