import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;

public class RecoverNative extends GhidraScript {
    private boolean isTargetFunction(String functionName) {
        return functionName.contains("YYGameMemory") ||
            functionName.contains("YYUnity") ||
            functionName.contains("YYIslandRoute") ||
            functionName.equals("RussIslandRouteOverlaySetEnabled") ||
            functionName.equals("RussIslandRouteOverlayShutdown");
    }

    private boolean isRuntimeDispatcher(Function function) {
        long entryOffset = function.getEntryPoint().getOffset();
        return entryOffset == 0x17098L || entryOffset == 0x17184L ||
            entryOffset == 0x17720L || entryOffset == 0x195a8L ||
            entryOffset == 0x19cf0L || entryOffset == 0x19de8L ||
            entryOffset == 0x1a0f4L || entryOffset == 0x1a2d8L ||
            entryOffset == 0x1a330L ||
            entryOffset == 0x1a400L || entryOffset == 0x1a480L ||
            entryOffset == 0x1a4e8L || entryOffset == 0x1a540L ||
            entryOffset == 0x1a5b0L || entryOffset == 0x1a730L ||
            entryOffset == 0x1a7b8L || entryOffset == 0x1aaa4L ||
            entryOffset == 0x1ab08L || entryOffset == 0x1abecL ||
            entryOffset == 0x1ac8cL || entryOffset == 0x1ad7cL ||
            entryOffset == 0x1ae10L || entryOffset == 0x1af00L ||
            entryOffset == 0x1af60L || entryOffset == 0x1b47cL ||
            entryOffset == 0x1b664L;
    }

    @Override
    public void run() throws Exception {
        String[] arguments = getScriptArgs();
        if (arguments.length != 1) {
            throw new IllegalArgumentException("Expected output file path");
        }

        File outputFile = new File(arguments[0]);
        File parentDirectory = outputFile.getParentFile();
        if (parentDirectory != null && !parentDirectory.exists() && !parentDirectory.mkdirs()) {
            throw new IllegalStateException("Unable to create output directory");
        }

        DecompInterface decompiler = new DecompInterface();
        decompiler.setSimplificationStyle("decompile");
        if (!decompiler.openProgram(currentProgram)) {
            throw new IllegalStateException("Unable to open program for decompilation");
        }

        int recoveredCount = 0;
        List<Function> allFunctions = new ArrayList<Function>();
        List<Function> targetFunctions = new ArrayList<Function>();
        FunctionIterator functions = currentProgram.getFunctionManager().getFunctions(true);
        while (functions.hasNext() && !monitor.isCancelled()) {
            Function function = functions.next();
            allFunctions.add(function);
            if (isTargetFunction(function.getName()) || isRuntimeDispatcher(function)) {
                targetFunctions.add(function);
            }
        }

        try (PrintWriter writer = new PrintWriter(outputFile, "UTF-8")) {
            writer.println("/* Generated by Ghidra from RussOriginal.dylib. */");
            for (Function function : targetFunctions) {
                String functionName = function.getName();
                DecompileResults result = decompiler.decompileFunction(function, 120, monitor);
                if (!result.decompileCompleted() || result.getDecompiledFunction() == null) {
                    writer.printf("/* Unable to decompile %s at %s */%n%n", functionName, function.getEntryPoint());
                    continue;
                }

                writer.printf("/* %s at %s */%n", functionName, function.getEntryPoint());
                writer.println(result.getDecompiledFunction().getC());
                writer.println();
                recoveredCount++;
            }
            writer.printf("/* Recovered functions: %d */%n", recoveredCount);
            if (recoveredCount == 0) {
                writer.println("/* Target symbols were not retained by the importer. */");
                writer.println("/* Function inventory for the next recovery pass: */");
                for (Function function : allFunctions) {
                    writer.printf("/* %s at %s */%n", function.getName(), function.getEntryPoint());
                }
            }
        } finally {
            decompiler.dispose();
        }
    }
}
