/* Generated by Ghidra from Ciyue0818.dylib. */
/* Evidence-selected function offsets: [] */
/* FUN_0000a474 at 0000a474 */

void FUN_0000a474(void)

{
  char cVar1;
  bool bVar2;
  byte bVar3;
  byte bVar4;
  ulong uVar5;
  dispatch_time_t dVar6;
  
  FUN_001bd0a0();
  FUN_00222a24();
  FUN_001a5048();
  bVar3 = FUN_001ad868();
  bVar4 = FUN_00225d80();
  uVar5 = FUN_0022298c();
  if ((uVar5 & 1) == 0) {
    DAT_004b128b = bVar3 & bVar4 ^ 1;
    if ((bVar3 & bVar4 & 1) != 0) {
      return;
    }
  }
  else {
    DAT_004b128b = 1;
  }
  do {
    if (DAT_004b128c != '\0') {
      ClearExclusiveLocal();
      return;
    }
    cVar1 = '\x01';
    bVar2 = (bool)ExclusiveMonitorPass(0x4b128c,0x10);
    if (bVar2) {
      DAT_004b128c = '\x01';
      cVar1 = ExclusiveMonitorsStatus();
    }
  } while (cVar1 != '\0');
  dVar6 = _dispatch_time(0,250000000);
  _dispatch_after(dVar6,PTR___dispatch_main_q_004a0218,&PTR___NSConcreteGlobalBlock_004a0450);
  return;
}



/* FUN_0000a528 at 0000a528 */

/* WARNING: Function: _objc_retainAutoreleasedReturnValue replaced with injection:
   _objc_retain_fixup */
/* WARNING: Function: _objc_release replaced with injection: _objc_release_fixup */

undefined8 FUN_0000a528(void)

{
  ID IVar1;
  ID self;
  SEL extraout_x1;
  SEL extraout_x1_00;
  
  ___cxa_begin_catch();
  IVar1 = std::terminate();
  FUN_00239850();
  FUN_0000a474();
  DAT_004afaf8 = 0;
  self = _B3m::mtkView(IVar1,extraout_x1);
  objc_stub::setEnableSetNeedsDisplay_(self,0);
  IVar1 = _B3m::mtkView(IVar1,extraout_x1_00);
  objc_stub::setPaused_(IVar1,1);
  return 0;
}



/* hookui_pauseRendering at 0000a538 */

/* WARNING: Function: _objc_retainAutoreleasedReturnValue replaced with injection:
   _objc_retain_fixup */
/* WARNING: Function: _objc_release replaced with injection: _objc_release_fixup */
/* Function Stack Size: 0x10 bytes */

void _B3m::hookui_pauseRendering(ID param_1,SEL param_2)

{
  ID IVar1;
  
  FUN_00239850();
  FUN_0000a474();
  DAT_004afaf8 = 0;
  IVar1 = mtkView(param_1);
  objc_stub::setEnableSetNeedsDisplay_(IVar1,0);
  IVar1 = mtkView(param_1);
  objc_stub::setPaused_(IVar1,1);
  return;
}



/* hookui_resumeRendering at 0000a5d4 */

/* WARNING: Function: _objc_retainAutoreleasedReturnValue replaced with injection:
   _objc_retain_fixup */
/* WARNING: Function: _objc_release replaced with injection: _objc_release_fixup */
/* Function Stack Size: 0x10 bytes */

void _B3m::hookui_resumeRendering(ID param_1,SEL param_2)

{
  int iVar1;
  ID IVar2;
  dispatch_time_t dVar3;
  undefined *local_48;
  undefined8 local_40;
  code *local_38;
  undefined *puStack_30;
  ID local_28;
  
  iVar1 = FUN_0000a6dc();
  if (iVar1 != 0) {
    DAT_004afaf8 = 1;
    IVar2 = mtkView(param_1);
    objc_stub::setEnableSetNeedsDisplay_(IVar2,0);
    IVar2 = mtkView(param_1);
    objc_stub::setPaused_(IVar2,0);
    hookui_updateCaptureProtection(param_1);
    dVar3 = _dispatch_time(0,200000000);
    local_48 = PTR___NSConcreteStackBlock_004a01f8;
    local_40 = DAT_0029bee0;
    local_38 = FUN_0000a75c;
    puStack_30 = &DAT_004a03b0;
    local_28 = param_1;
    _dispatch_after(dVar3,PTR___dispatch_main_q_004a0218,&local_48);
  }
  return;
}



/* FUN_0000a6dc at 0000a6dc */

/* WARNING: Function: _objc_retainAutoreleasedReturnValue replaced with injection:
   _objc_retain_fixup */
/* WARNING: Function: _objc_release replaced with injection: _objc_release_fixup */

bool FUN_0000a6dc(void)

{
  bool bVar1;
  ID IVar2;
  
  IVar2 = UIApplication::sharedApplication((ID)PTR__OBJC_CLASS___UIApplication_004aeb68);
  if (IVar2 == 0) {
    bVar1 = true;
  }
  else {
    IVar2 = UIApplication::applicationState(IVar2);
    bVar1 = IVar2 == 0;
  }
  return bVar1;
}



/* FUN_0000a75c at 0000a75c */

/* WARNING: Function: _objc_retainAutoreleasedReturnValue replaced with injection:
   _objc_retain_fixup */
/* WARNING: Function: _objc_release replaced with injection: _objc_release_fixup */

undefined8 FUN_0000a75c(long param_1)

{
  undefined8 uVar1;
  ID IVar2;
  
  uVar1 = FUN_0000a6dc();
  if ((int)uVar1 == 0) {
    return uVar1;
  }
  IVar2 = objc_stub::view(*(ID *)(param_1 + 0x20));
  IVar2 = objc_stub::window(IVar2);
  if (IVar2 != 0) {
    IVar2 = objc_stub::mtkView(*(ID *)(param_1 + 0x20));
    IVar2 = objc_stub::window(IVar2);
    if (IVar2 == 0) {
      return 0;
    }
    IVar2 = objc_stub::mtkView(*(ID *)(param_1 + 0x20));
    FUN_0000a864(IVar2);
  }
  return 0;
}



/* FUN_0000a864 at 0000a864 */

/* WARNING: Function: _objc_retain replaced with injection: _objc_retain_fixup */
/* WARNING: Function: _objc_retainAutoreleasedReturnValue replaced with injection:
   _objc_retain_fixup */
/* WARNING: Function: _objc_release replaced with injection: _objc_release_fixup */

undefined8 FUN_0000a864(undefined1 param_1 [16],double param_2,ID param_3)

{
  ID IVar1;
  double dVar2;
  double extraout_d0;
  double dVar3;
  double dVar4;
  
  if ((param_3 != 0) && (IVar1 = objc_stub::window(param_3), IVar1 != 0)) {
    dVar2 = (double)FUN_0000c988(param_3);
    dVar4 = 1.0;
    if (1.0 <= dVar2 + dVar2) {
      dVar4 = dVar2 + dVar2;
    }
    dVar2 = 1.0;
    if (1.0 <= param_2 + param_2) {
      dVar2 = param_2 + param_2;
    }
    objc_stub::drawableSize(param_3);
    dVar3 = 0.5;
    if ((0.5 < ABS(extraout_d0 - dVar4)) ||
       (objc_stub::drawableSize(param_3), 0.5 < ABS(dVar3 - dVar2))) {
      objc_stub::setDrawableSize_(param_3,dVar4,dVar2);
    }
  }
  return 0;
}



/* hookui_captureProtectionActive at 0000a960 */

/* WARNING: Function: _objc_retainAutoreleasedReturnValue replaced with injection:
   _objc_retain_fixup */
/* WARNING: Function: _objc_release replaced with injection: _objc_release_fixup */
/* Function Stack Size: 0x10 bytes */

bool _B3m::hookui_captureProtectionActive(ID param_1,SEL param_2)

{
  bool bVar1;
  ID IVar2;
  
  if (DAT_004afbe8 == '\x01') {
    IVar2 = UIScreen::mainScreen((ID)PTR__OBJC_CLASS___UIScreen_004aeba8);
    IVar2 = UIScreen::isCaptured(IVar2);
    bVar1 = (bool)IVar2;
  }
  else {
    bVar1 = 0;
  }
  return bVar1;
}



/* hookui_syncPanelGlassFrame:visible: at 0000a9e0 */

/* WARNING: Function: _objc_retainAutoreleasedReturnValue replaced with injection:
   _objc_retain_fixup */
/* WARNING: Function: _objc_release replaced with injection: _objc_release_fixup */
/* Function Stack Size: 0x34 bytes */

void _B3m::hookui_syncPanelGlassFrame_visible_(ID param_1,SEL param_2,CGRect param_3,bool param_4)

{
  bool bVar1;
  ID IVar2;
  ulong uVar3;
  undefined8 uVar4;
  double dVar5;
  double dVar6;
  double dVar7;
  double dVar8;
  undefined *local_a8;
  undefined8 local_a0;
  code *local_98;
  undefined *puStack_90;
  undefined1 auStack_88 [8];
  double local_80;
  double dStack_78;
  double local_70;
  double dStack_68;
  undefined1 local_60;
  undefined1 auStack_58 [8];
  
  dVar8 = param_3.field1_0x10.field1_0x8;
  dVar7 = param_3.field1_0x10.field0_0x0;
  dVar6 = param_3.field0_0x0.field1_0x8;
  dVar5 = param_3.field0_0x0.field0_0x0;
  IVar2 = NSThread::isMainThread((ID)PTR__OBJC_CLASS___NSThread_004aeb60);
  if ((IVar2 & 1) != 0) {
    IVar2 = panelGlassView(param_1);
    if (IVar2 != 0) {
      if (((param_4 == 0) || (uVar3 = _CGRectIsEmpty(dVar5,dVar6,dVar7,dVar8), (uVar3 & 1) != 0)) ||
         (bVar1 = hookui_captureProtectionActive(param_1), (bVar1 & 1) != 0)) {
        uVar4 = 1;
      }
      else {
        objc_stub::frame(IVar2);
        uVar3 = _CGRectEqualToRect();
        if ((uVar3 & 1) == 0) {
          objc_stub::setFrame_(IVar2,dVar5,dVar6,dVar7,dVar8);
        }
        uVar4 = 0;
      }
      objc_stub::setHidden_(IVar2,uVar4);
    }
    return;
  }
  _objc_initWeak(auStack_58,param_1);
  local_a8 = PTR___NSConcreteStackBlock_004a01f8;
  local_a0 = DAT_0029bee0;
  local_98 = FUN_0000ab74;
  puStack_90 = &DAT_004a03e0;
  _objc_copyWeak(auStack_88,auStack_58);
  local_60 = (undefined1)param_4;
  local_80 = dVar5;
  dStack_78 = dVar6;
  local_70 = dVar7;
  dStack_68 = dVar8;
  _dispatch_async(PTR___dispatch_main_q_004a0218,&local_a8);
  _objc_destroyWeak(auStack_88);
  _objc_destroyWeak(auStack_58);
  return;
}



/* hookui_updateCaptureProtection at 0000abd8 */

/* WARNING: Function: _objc_retainAutoreleasedReturnValue replaced with injection:
   _objc_retain_fixup */
/* WARNING: Function: _objc_release replaced with injection: _objc_release_fixup */
/* Function Stack Size: 0x10 bytes */

void _B3m::hookui_updateCaptureProtection(ID param_1,SEL param_2)

{
  bool bVar1;
  ID IVar2;
  long lVar3;
  undefined8 uVar4;
  
  bVar1 = hookui_captureProtectionActive(param_1);
  if (bVar1 != 0) {
    FUN_00239850();
    FUN_0000a474();
  }
  IVar2 = mtkView(param_1);
  uVar4 = 0;
  if (bVar1 == 0) {
    uVar4 = 0x3ff0000000000000;
  }
  objc_stub::setAlpha_(IVar2,uVar4);
  IVar2 = _g03(param_1);
  IVar2 = objc_stub::view(IVar2);
  objc_stub::setHidden_(IVar2,(ulong)bVar1);
  if (bVar1 != 0) {
    IVar2 = panelGlassView(param_1);
    objc_stub::setHidden_(IVar2,1);
    FUN_00251e48(0);
    lVar3 = FUN_0026b618();
    if (lVar3 != 0) {
      lVar3 = FUN_0026b924();
      *(undefined1 *)(lVar3 + 0x128) = 0;
    }
  }
  return;
}



/* hookui_screenCaptureDidChange: at 0000ad08 */

/* Function Stack Size: 0x18 bytes */

void _B3m::hookui_screenCaptureDidChange_(ID param_1,SEL param_2,ID param_3)

{
  undefined *local_38;
  undefined8 local_30;
  undefined1 *local_28;
  undefined *puStack_20;
  ID local_18;
  
  local_38 = PTR___NSConcreteStackBlock_004a01f8;
  local_30 = DAT_0029bee0;
  local_28 = &LAB_0000ad60;
  puStack_20 = &DAT_004a03b0;
  local_18 = param_1;
  _dispatch_async(PTR___dispatch_main_q_004a0218,&local_38);
  return;
}



/* hookui_applicationWillResignActive: at 0000ad68 */

/* Function Stack Size: 0x18 bytes */

ID __objc_msgSend_stub _B3m::hookui_applicationWillResignActive_(ID self,...)

{
  ID IVar1;
  
  IVar1 = (*(code *)PTR__objc_msgSend_004a0008)(self,PTR_s_hookui_pauseRendering_004add48);
  return IVar1;
}



/* hookui_applicationDidEnterBackground: at 0000ad6c */

/* Function Stack Size: 0x18 bytes */

ID __objc_msgSend_stub _B3m::hookui_applicationDidEnterBackground_(ID self,...)

{
  ID IVar1;
  
  IVar1 = (*(code *)PTR__objc_msgSend_004a0008)(self,PTR_s_hookui_pauseRendering_004add48);
  return IVar1;
}



/* hookui_applicationWillTerminate: at 0000ad70 */

/* Function Stack Size: 0x18 bytes */

ID __objc_msgSend_stub _B3m::hookui_applicationWillTerminate_(ID self,...)

{
  ID IVar1;
  
  IVar1 = (*(code *)PTR__objc_msgSend_004a0008)(self,PTR_s_hookui_pauseRendering_004add48);
  return IVar1;
}



/* hookui_applicationDidBecomeActive: at 0000ad74 */

/* Function Stack Size: 0x18 bytes */

ID __objc_msgSend_stub _B3m::hookui_applicationDidBecomeActive_(ID self,...)

{
  ID IVar1;
  
  IVar1 = (*(code *)PTR__objc_msgSend_004a0008)(self,PTR_s_hookui_resumeRendering_004add58);
  return IVar1;
}



/* hookui_refreshSpearKillQuickButton at 002537f8 */

/* Function Stack Size: 0x10 bytes */

void _E5w::hookui_refreshSpearKillQuickButton(ID param_1,SEL param_2)

{
  return;
}



/* hookui_refreshDefogQuickButton at 002537fc */

/* Function Stack Size: 0x10 bytes */

void _E5w::hookui_refreshDefogQuickButton(ID param_1,SEL param_2)

{
  return;
}



/* hookui_autoSaveParams at 00255b54 */

/* Function Stack Size: 0x10 bytes */

void _E5w::hookui_autoSaveParams(ID param_1,SEL param_2)

{
  _dispatch_async(PTR___dispatch_main_q_004a0218,&PTR___NSConcreteGlobalBlock_004a1838);
  return;
}



/* hookui_autoSaveParams at 002985a0 */

ID __objc_msgSend_stub objc_stub::hookui_autoSaveParams(ID self,...)

{
  ID IVar1;
  
  IVar1 = (*(code *)PTR__objc_msgSend_004a0008)(self,PTR_s_hookui_autoSaveParams_004add38);
  return IVar1;
}



/* hookui_captureProtectionActive at 002985c0 */

ID __objc_msgSend_stub objc_stub::hookui_captureProtectionActive(ID self,...)

{
  ID IVar1;
  
  IVar1 = (*(code *)PTR__objc_msgSend_004a0008)(self,PTR_s_hookui_captureProtectionActive_004add40);
  return IVar1;
}



/* hookui_resumeRendering at 00298620 */

ID __objc_msgSend_stub objc_stub::hookui_resumeRendering(ID self,...)

{
  ID IVar1;
  
  IVar1 = (*(code *)PTR__objc_msgSend_004a0008)(self,PTR_s_hookui_resumeRendering_004add58);
  return IVar1;
}



/* hookui_syncPanelGlassFrame:visible: at 00298640 */

ID __objc_msgSend_stub objc_stub::hookui_syncPanelGlassFrame_visible_(ID self,...)

{
  ID IVar1;
  
  IVar1 = (*(code *)PTR__objc_msgSend_004a0008)
                    (self,PTR_s_hookui_syncPanelGlassFrame_visib_004add60);
  return IVar1;
}



/* hookui_updateCaptureProtection at 00298660 */

ID __objc_msgSend_stub objc_stub::hookui_updateCaptureProtection(ID self,...)

{
  ID IVar1;
  
  IVar1 = (*(code *)PTR__objc_msgSend_004a0008)(self,PTR_s_hookui_updateCaptureProtection_004add68);
  return IVar1;
}



/* Recovered functions: 23 */
