/* Generated by Ghidra from Ciyue0818.dylib. */
/* Evidence strings: [pointsList, Chest, PlayerA.png, DrawPathPointLine, Loot, InitLoadLine, UGC2FOV, UGC2FirstFOV, Item, set_fog, Unknown Item, FindPathLineCtrl, 物资, IDBNHPMAGCN, UGCObjectCoffin, Monster, Enemy, DGFGHBCDENH, CameraFollow, DCODHFKCBGO, set_fogDensity, lineRender] */
/* Evidence-selected function offsets: [1623448, 1069584, 1618968, 419204, 2707500, 2708396, 2709548, 1515664, 2732576, 1534620, 2605484, 1640340, 1423512, 2710052, 1535384, 2708408, 2710328, 1536768, 2710064, 871188, 1534220, 292504, 2709428, 143004, 1037968, 1533620, 476960, 2719488, 679968, 1091516, 284596, 1533220, 1255456, 2710940, 2707356, 1532320, 2709008, 1505836, 767536, 54972, 1065388, 2708372, 1387560, 1520552, 2602520, 2709224, 864716, 503108, 1534420, 1532116, 549708, 1633756, 663628, 1303380, 2719968, 2725856, 2710244, 2707428, 1528792, 5320193, 5323009, 5320195, 1534020, 1619020, 2708348, 2709116, 734172, 290140, 2708336, 1537100, 2710472, 93792, 1389556, 2603968, 1619440, 2720704, 2721472, 2733888, 1533820, 686948, 928764, 1459172, 768376, 1519588, 1534820, 2601812, 1633900, 1640940, 561008, 109176, 1537772, 1533420, 1660132, 1189356, 1531880, 1535720] */
/* FUN_0006e748 at 0006e748 */

undefined8
FUN_0006e748(undefined1 param_1 [16],uint param_2,uint param_3,long param_4,uint *param_5)

{
  undefined8 uVar1;
  long lVar2;
  uint uVar3;
  
  if (param_5 != (uint *)0x0) {
    param_5[0] = 0;
    param_5[1] = 0;
    param_5[2] = 0;
  }
  uVar1 = 0;
  if (((param_4 != 0) && (param_5 != (uint *)0x0)) &&
     (DAT_004b2c40 != (code *)0x0 && DAT_004b2c50 != (code *)0x0)) {
    lVar2 = (*DAT_004b2c40)(param_4);
    uVar1 = 0;
    if (lVar2 != 0) {
      uVar3 = (*DAT_004b2c50)();
      uVar1 = 0;
      if (((uVar3 & 0x7fffffff) < 0x7f800000 && (param_2 & 0x7fffffff) < 0x7f800000) &&
         ((param_3 & 0x7fffffff) < 0x7f800000)) {
        *param_5 = uVar3;
        param_5[1] = param_2;
        uVar1 = 1;
        param_5[2] = param_3;
      }
    }
  }
  return uVar1;
}



/* FUN_000723c4 at 000723c4 */

/* WARNING: Function: _objc_retain replaced with injection: _objc_retain_fixup */
/* WARNING: Function: _objc_release replaced with injection: _objc_release_fixup */
/* WARNING: Type propagation algorithm not settling */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void FUN_000723c4(ulong param_1)

{
  char *pcVar1;
  void *pvVar2;
  byte bVar3;
  byte bVar4;
  char cVar5;
  long *plVar6;
  undefined8 *puVar7;
  undefined8 *puVar8;
  double dVar9;
  bool bVar10;
  byte bVar11;
  bool bVar12;
  bool bVar13;
  bool bVar14;
  bool bVar15;
  byte bVar16;
  int iVar17;
  uint uVar18;
  int iVar19;
  int iVar20;
  int iVar21;
  ID IVar22;
  long lVar23;
  long lVar24;
  undefined8 uVar25;
  long lVar26;
  ulong uVar27;
  long lVar28;
  undefined *puVar29;
  undefined8 uVar30;
  long *plVar31;
  long *plVar32;
  byte bVar33;
  byte bVar34;
  long *plVar35;
  long *plVar36;
  char *pcVar37;
  undefined8 *puVar38;
  uint uVar39;
  uint uVar40;
  float fVar41;
  double dVar42;
  undefined8 uVar43;
  uint uVar44;
  double dVar45;
  double dVar46;
  undefined8 uVar47;
  uint uVar48;
  double dVar49;
  undefined8 uVar50;
  undefined8 uVar51;
  double dVar52;
  undefined8 uVar53;
  double dVar54;
  float fVar55;
  double dVar56;
  ulong local_4c0;
  long *local_480;
  undefined8 *puStack_478;
  undefined8 *puStack_470;
  undefined8 local_460;
  undefined8 uStack_458;
  undefined8 uStack_450;
  undefined8 uStack_448;
  float local_440;
  undefined8 local_430;
  undefined8 uStack_428;
  undefined8 uStack_420;
  undefined8 uStack_418;
  float local_410;
  undefined8 *local_400;
  undefined8 *puStack_3f8;
  undefined8 local_3f0 [2];
  undefined8 *local_3e0;
  undefined8 *puStack_3d8;
  undefined8 local_3d0;
  void *local_3c8;
  undefined8 uStack_3c0;
  long local_3b8;
  undefined8 local_3b0;
  long *plStack_3a8;
  ulong local_3a0;
  undefined4 local_394;
  ulong local_390;
  uint local_384;
  undefined8 local_380;
  uint local_378;
  long *local_370;
  undefined8 local_368;
  undefined8 *puStack_360;
  undefined8 local_358;
  undefined4 local_350;
  undefined8 local_348;
  undefined4 local_340;
  undefined8 local_338;
  long local_330;
  undefined8 uStack_328;
  undefined4 local_320;
  byte local_31c;
  undefined8 local_318;
  undefined8 uStack_310;
  void *local_308;
  void *local_300;
  undefined8 local_2f8;
  undefined8 local_2f0;
  undefined4 local_2e8;
  undefined8 local_2e0;
  undefined4 local_2d8;
  ulong local_2d0;
  int local_2c8;
  undefined4 uStack_2c4;
  undefined4 uStack_2c0;
  undefined4 uStack_2bc;
  undefined4 uStack_2b8;
  undefined8 local_2b0;
  undefined8 local_2a8;
  undefined4 local_2a0;
  long *local_298;
  long *local_290;
  long local_270;
  undefined8 local_248;
  undefined8 local_240;
  undefined4 local_238;
  void *local_230;
  void *local_228;
  uint local_214;
  char local_20c;
  uint local_204;
  int local_200;
  int local_1fc;
  void *local_1e8;
  long *local_1e0;
  byte local_1d1;
  undefined *local_1d0;
  long lStack_1c8;
  undefined1 *local_1c0;
  undefined8 *puStack_1b8;
  long *local_1b0;
  long lStack_1a8;
  ulong local_1a0;
  void *local_198;
  long *plStack_190;
  long *local_188;
  undefined1 uStack_180;
  undefined7 uStack_17f;
  undefined8 local_178;
  undefined1 local_170;
  int local_16c;
  byte local_168;
  undefined8 local_160;
  undefined8 local_158;
  undefined8 uStack_150;
  undefined4 local_148;
  long *local_140;
  long *plStack_138;
  ulong local_130;
  void *local_128;
  undefined8 uStack_120;
  long lStack_118;
  undefined8 uStack_110;
  undefined8 uStack_108;
  undefined8 local_100;
  undefined8 uStack_f8;
  undefined8 uStack_f0;
  undefined8 uStack_e8;
  undefined1 local_e0;
  undefined5 uStack_dc;
  undefined3 local_d7;
  undefined5 uStack_d4;
  undefined8 local_cc;
  undefined8 uStack_c4;
  undefined4 local_bc;
  undefined8 local_b8;
  undefined1 local_b0;
  
  IVar22 = NSThread::isMainThread((ID)PTR__OBJC_CLASS___NSThread_004aeb60);
  if ((int)IVar22 == 0) {
    return;
  }
  if (param_1 < 0x100001) {
    return;
  }
  if ((param_1 & 7) != 0) {
    return;
  }
  lVar23 = std::chrono::steady_clock::now();
  local_3e0 = (undefined8 *)0x0;
  puStack_3d8 = (undefined8 *)0x0;
  local_3d0 = 0;
  local_400 = (undefined8 *)0x0;
  puStack_3f8 = (undefined8 *)0x0;
  local_3f0[0] = 0;
  uStack_428 = 0;
  local_430 = 0;
  uStack_418 = 0;
  uStack_420 = 0;
  local_410 = 1.0;
  uStack_458 = 0;
  local_460 = 0;
  uStack_448 = 0;
  uStack_450 = 0;
  local_440 = 1.0;
  FUN_00166734(&local_3e0,0x80);
  FUN_00166734(&local_400,0x40);
  FUN_00197978(&local_430,(long)(32.0 / local_410));
  FUN_00142e10(&local_460,(long)(32.0 / local_440));
  dVar9 = DAT_0044cb20;
  dVar54 = (double)lVar23 / DAT_0044cb20;
  lVar24 = std::chrono::steady_clock::now();
  plVar6 = DAT_004b00c0;
  lVar23 = DAT_004aff08;
  dVar56 = (double)lVar24 / dVar9;
  do {
    uVar48 = DAT_004e7750;
    cVar5 = '\x01';
    bVar14 = (bool)ExclusiveMonitorPass(0x4e7750,0x10);
    if (bVar14) {
      cVar5 = ExclusiveMonitorsStatus();
      DAT_004e7750 = DAT_004e7750 & 0xfffffff3;
    }
  } while (cVar5 != '\0');
  if ((uVar48 >> 2 & 1) != 0) {
    DAT_004b2b60 = 0.0;
  }
  if ((uVar48 >> 3 & 1) != 0) {
    DAT_004b2b68 = 0.0;
  }
  if (DAT_004aff08 != DAT_004e9710) {
    DAT_004e9710 = DAT_004aff08;
    DAT_004b2b60 = 0.0;
    DAT_004b2b68 = 0.0;
    DAT_004b2b70 = 0.0;
    DAT_004b2b78 = 0.0;
    FUN_00195310(&DAT_004b2b38);
  }
  plVar32 = DAT_004b00c0;
  if (DAT_004b22c0 == '\x01') {
    bVar11 = 0;
    if (DAT_004b2360 == '\x05') {
      bVar11 = DAT_004b235f;
    }
    bVar16 = 0;
    if (DAT_004b2360 == '\x06') {
      bVar16 = DAT_004b235f;
    }
  }
  else {
    bVar11 = 0;
    bVar16 = 0;
  }
  bVar15 = DAT_004afd58 == '\x01';
  bVar14 = 3 < DAT_004b0164 || DAT_004b0164 == 2;
  if ((((DAT_004afbc8 & 1) == 0) && ((DAT_004afd56 & 1) == 0)) && ((DAT_004b0600 & 1) == 0)) {
    bVar34 = 1;
    if (((DAT_004afbcd & 1) == 0) && ((DAT_004afbd7 & 1) == 0)) {
      bVar34 = DAT_004afbd9 | DAT_004afd3c;
    }
  }
  else {
    bVar34 = 1;
  }
  bVar33 = 1;
  if (((DAT_004afbce & 1) == 0) && ((DAT_004afd3c & 1) == 0)) {
    bVar33 = DAT_004afbd9;
  }
  bVar3 = bVar34 | (bVar15 && bVar14) | bVar11;
  bVar4 = bVar33 | (bVar15 && DAT_004b0164 == 3) | bVar16;
  dVar52 = DAT_0044ce40;
  dVar42 = DAT_0044cc60;
  dVar45 = DAT_0044ce08;
  if (DAT_004afd3c == 0) {
LAB_00072694:
    if ((DAT_004b0600 & 1) == 0) {
      dVar42 = dVar52;
    }
  }
  else {
    dVar52 = DAT_004b2b78;
    if (DAT_004b2b78 <= DAT_004b2b70) {
      dVar52 = DAT_004b2b70;
    }
    bVar10 = false;
    bVar12 = true;
    bVar13 = false;
    if (dVar56 - dVar52 <= 0.25) {
      bVar10 = false;
      bVar12 = false;
      bVar13 = true;
      if (!NAN(dVar52)) {
        bVar10 = dVar52 < 0.0;
        bVar12 = dVar52 == 0.0;
        bVar13 = false;
      }
    }
    dVar52 = DAT_0044cc60;
    if ((((!bVar12 && bVar10 == bVar13) || ((DAT_004afbc8 & 1) != 0)) || ((DAT_004afbcd & 1) != 0))
       || (((DAT_004afbd7 & 1) != 0 ||
           (((DAT_004afbd9 | DAT_004afbce |
             (bVar15 && (bVar14 || DAT_004b0164 == 3)) | bVar11 | bVar16) & 1) != 0))))
    goto LAB_00072694;
    if (DAT_004b0600 == 0) {
      dVar42 = 0.25;
      dVar45 = 0.25;
    }
  }
  if ((bVar34 & 1) == 0) {
    dVar42 = DAT_0044ce48;
  }
  if (DAT_004afd3c == 0) {
    dVar45 = DAT_0044ce50;
  }
  if ((bVar33 & 1) == 0) {
    dVar45 = DAT_0044ce48;
  }
  if ((bVar3 & 1) == 0) {
    bVar11 = false;
  }
  else if (DAT_004b2b60 <= 0.0) {
    bVar11 = true;
  }
  else {
    bVar11 = dVar42 <= dVar56 - DAT_004b2b60;
  }
  bVar16 = DAT_004b0540;
  if ((bVar4 & 1) == 0) {
    bVar34 = 0;
  }
  else {
    bVar34 = dVar45 <= dVar56 - DAT_004b2b68 || DAT_004b2b68 <= 0.0;
    if ((bVar11 & bVar34) == 1) {
      bVar34 = DAT_004b0540 ^ 1;
      bVar16 = bVar34;
      bVar11 = DAT_004b0540;
    }
  }
  DAT_004b0540 = bVar16;
  if (((bVar11 | bVar34) & 1) != 0) {
    DAT_004e9719 = DAT_004e9718;
    DAT_004e9718 = DAT_004e9718 + 1 & 3;
  }
  if ((bVar3 & bVar4 & 1) == 0) {
    if ((bVar3 & 1) == 0) {
      DAT_004b2b70 = 0.0;
    }
    if ((bVar4 & 1) == 0) {
      DAT_004b2b78 = 0.0;
    }
  }
  dVar52 = DAT_0044ce48;
  if ((bVar11 & 1) == 0) {
LAB_0007292c:
    uVar48 = SUB84(dVar52,0);
    bVar16 = 1;
    if ((bVar34 & 1) == 0) goto LAB_00073a08;
LAB_00072934:
    dVar42 = dVar56;
    if (DAT_004b2b68 <= dVar56) {
      dVar52 = dVar56 - DAT_004b2b68;
      uVar48 = 0;
      bVar14 = false;
      bVar15 = false;
      bVar10 = false;
      if (0.0 < DAT_004b2b68) {
        bVar14 = false;
        bVar15 = false;
        bVar10 = true;
        if (!NAN(dVar52)) {
          bVar14 = dVar52 < 1.0;
          bVar15 = dVar52 == 1.0;
          bVar10 = false;
        }
      }
      if (bVar15 || bVar14 != bVar10) {
        dVar46 = 1.0;
        if (1.0 <= (double)(long)(dVar52 / dVar45)) {
          dVar46 = (double)(long)(dVar52 / dVar45);
        }
        dVar52 = DAT_004b2b68 + dVar45 * dVar46;
        if (dVar52 <= dVar56) {
          dVar42 = dVar52;
        }
      }
    }
    DAT_004b2b68 = dVar42;
    if (DAT_004e3188 != DAT_004b00c0) {
      lStack_1c8 = 0;
      local_1d0 = (undefined *)0x0;
      local_1c0 = (undefined1 *)0x0;
      DAT_004b2d98 = 0;
      DAT_004b2da0 = 0;
      DAT_004b2d90 = (long *)0x0;
      FUN_0016ec44(&DAT_004b2da8);
      DAT_004b2da8 = (undefined8 *)0x0;
      DAT_004b2db0 = (undefined8 *)0x0;
      DAT_004b2db8 = 0;
      lStack_1a8 = 0;
      puStack_1b8 = (undefined8 *)0x0;
      local_1b0 = (long *)0x0;
      FUN_000861ac(&puStack_1b8);
      DAT_004e971b = 0;
      puVar38 = local_400;
      puVar7 = puStack_3f8;
joined_r0x000739e4:
      while (puVar8 = local_400, puVar7 != local_400) {
        local_400 = puVar38;
        FUN_00086210(local_3f0,puVar7 + -0x25);
        puVar38 = local_400;
        puVar7 = puVar7 + -0x25;
        local_400 = puVar8;
      }
      puStack_3f8 = local_400;
      local_400 = puVar38;
      goto LAB_00073a08;
    }
    FUN_000448b4(&local_370);
    plVar32 = DAT_004b00c0;
    if (local_370 == DAT_004b00c0) {
      uVar25 = FUN_000449fc(&local_370);
      lVar24 = FUN_00044ac0(uVar25,uStack_310._4_4_);
      uVar18 = FUN_0013bcdc();
      if ((local_330 == 0) || ((int)uVar18 < 0)) goto LAB_00073970;
      if (uVar18 == 0) {
        lStack_1c8 = 0;
        local_1d0 = (undefined *)0x0;
        local_1c0 = (undefined1 *)0x0;
        DAT_004b2d98 = 0;
        DAT_004b2da0 = 0;
        DAT_004b2d90 = (long *)0x0;
        FUN_0016ec44(&DAT_004b2da8);
        DAT_004b2da8 = (undefined8 *)0x0;
        DAT_004b2db0 = (undefined8 *)0x0;
        DAT_004b2db8 = 0;
        lStack_1a8 = 0;
        puStack_1b8 = (undefined8 *)0x0;
        local_1b0 = (long *)0x0;
        FUN_000861ac(&puStack_1b8);
        DAT_004e971b = 0;
        bVar14 = local_370 == DAT_004b00c0;
      }
      else {
        local_3b0 = (long *)0x0;
        plStack_3a8 = (long *)((ulong)plStack_3a8 & 0xffffffff00000000);
        uVar40 = 0;
        if (DAT_004b2c40 == (code *)0x0) {
          uVar44 = 0;
          uVar39 = 0;
        }
        else {
          lVar26 = (*DAT_004b2c40)(param_1);
          uVar44 = 0;
          uVar39 = 0;
          uVar40 = 0;
          if (lVar26 != 0) {
            uVar40 = uVar48;
            uVar44 = 0;
            uVar39 = (*DAT_004b2c50)();
            local_3b0 = (long *)CONCAT44(uVar44,uVar39);
            plStack_3a8 = (long *)CONCAT44(plStack_3a8._4_4_,uVar40);
          }
        }
        bVar14 = false;
        if ((((uVar39 & 0x7fffffff) < 0x7f800000) && ((uVar44 & 0x7fffffff) < 0x7f800000)) &&
           ((uVar40 & 0x7fffffff) < 0x7f800000)) {
          fVar41 = DAT_004afbfc;
          if ((0x7fffffff < (uint)DAT_004afbfc || 0x7e < (int)ABS(DAT_004afbfc) - 0x800000U >> 0x18)
              && 0x7ffffe < (int)DAT_004afbfc - 1U) {
            fVar41 = 100.0;
          }
          fVar55 = 2000.0;
          if (fVar41 <= 2000.0) {
            fVar55 = fVar41;
          }
          lVar26 = std::chrono::steady_clock::now();
          FUN_0016ecac((double)lVar26 / dVar9);
          FUN_0016ed34(&local_298);
          if (((DAT_004b2d90 != plVar32) || (DAT_004b2d98 != lVar24)) ||
             (((uint)DAT_004b2da0 != uVar18 ||
              ((DAT_004b2da0 < 0 || ((int)uVar18 < DAT_004b2da0._4_4_)))))) {
            puStack_1b8 = (undefined8 *)0x0;
            local_1c0 = (undefined1 *)0x0;
            lStack_1a8 = 0;
            local_1b0 = (undefined8 *)0x0;
            lStack_1c8 = 0;
            local_1d0 = (undefined *)0x0;
            DAT_004b2d98 = 0;
            DAT_004b2da0 = 0;
            DAT_004b2d90 = (long *)0x0;
            FUN_0016ec44(&DAT_004b2da8);
            DAT_004b2db0 = local_1b0;
            DAT_004b2da8 = puStack_1b8;
            DAT_004b2db8 = lStack_1a8;
            lStack_1a8 = 0;
            local_1b0 = (long *)0x0;
            puStack_1b8 = (undefined8 *)0x0;
            FUN_000861ac(&puStack_1b8);
            DAT_004b2d90 = plVar32;
            DAT_004b2da0 = CONCAT44(DAT_004b2da0._4_4_,uVar18);
            uVar48 = uVar18;
            if (0xff < uVar18) {
              uVar48 = 0x100;
            }
            DAT_004b2d98 = lVar24;
            FUN_00166734(&DAT_004b2da8,uVar48);
          }
          lVar28 = std::chrono::steady_clock::now();
          uVar43 = _UNK_0044cf38;
          uVar25 = _DAT_0044cf30;
          if (DAT_004b2da0._4_4_ < (int)uVar18) {
            dVar42 = (double)lVar28 / dVar9 + DAT_0044ce60;
            uVar48 = 0;
            while( true ) {
              lVar28 = std::chrono::steady_clock::now();
              iVar17 = DAT_004b2da0._4_4_;
              if (dVar42 <= (double)lVar28 / dVar9) break;
              DAT_004b2da0 = CONCAT44(DAT_004b2da0._4_4_ + 1,(uint)DAT_004b2da0);
              local_390 = local_390 & 0xffffffff00000000;
              local_3c8 = (void *)0x0;
              uVar27 = FUN_0013bd48(lVar24,iVar17,&local_390,&local_3c8);
              if ((uVar27 & 1) == 0) goto LAB_00073970;
              if (((((int)local_390 != 0) && ((void *)0x100000 < local_3c8)) &&
                  (((ulong)local_3c8 & 7) == 0)) &&
                 (iVar17 = FUN_00044b28(local_3c8,local_330), iVar17 != 0)) {
                uVar30 = FUN_000fecf0(local_3c8);
                pvVar2 = local_3c8;
                local_16c = 0;
                local_168 = 0;
                lStack_1c8 = 0;
                local_1d0 = (undefined *)0x0;
                puStack_1b8 = (undefined8 *)0x0;
                local_1c0 = (undefined1 *)0x0;
                lStack_1a8 = 0;
                local_1b0 = (long *)0x0;
                local_1a0 = local_1a0 & 0xffffffffffff0000;
                plStack_190 = (long *)0x0;
                local_198 = (void *)0x0;
                uStack_180 = 0;
                local_188 = (long *)0x0;
                local_178._4_4_ = 0;
                local_170 = 0;
                uStack_17f = 0;
                local_178._0_4_ = 0;
                local_158 = 0;
                uStack_150 = 0;
                local_160 = 0;
                local_148 = 0;
                plStack_138 = (long *)0x0;
                local_140 = (long *)0x0;
                local_128 = (void *)0x0;
                local_130 = 0;
                lStack_118 = 0;
                uStack_120 = 0;
                uStack_108 = 0;
                uStack_110 = 0;
                uStack_f8 = 0;
                local_100 = 0;
                uStack_e8 = 0;
                uStack_f0 = 0;
                local_e0 = 0;
                uStack_d4 = 0;
                uStack_dc = 0;
                local_d7 = 0;
                uStack_c4 = uVar43;
                local_cc = uVar25;
                local_bc = 0;
                local_b8 = 0;
                local_b0 = 0;
                uVar27 = local_390 & 0xffffffff;
                local_1e8 = (void *)CONCAT17(local_1e8._7_1_,0xc0c095e1000000);
                local_1e8 = (void *)CONCAT44(local_1e8._4_4_,0xe1881cd0);
                FUN_0016f27c(&local_380,&local_1e8);
                uVar27 = FUN_00166c40(fVar55,param_1,pvVar2,uVar30,uVar27,1,&local_380,&local_3b0,
                                      &local_1d0);
                FUN_0016ed9c(&local_380);
                if ((uVar27 & 1) != 0) {
                  if ((-1 < (long)local_2d0) && (-1 < local_2c8)) {
                    local_1e8 = (void *)((ulong)local_1e8 & 0xffffffff00000000);
                    uVar27 = FUN_000d27d0((long)local_3c8 + (local_2d0 >> 0x20),&local_1e8,4);
                    if ((uVar27 & 1) != 0) {
                      uVar40 = (uint)local_1e8;
                      local_1e8 = (void *)((ulong)local_1e8 & 0xffffffff00000000);
                      uVar27 = FUN_000d27d0((long)local_3c8 + (long)local_2c8,&local_1e8,4);
                      if ((((uVar27 & 1) != 0) && (0xff67697f < (uint)local_1e8 - 0x989681)) &&
                         ((-0x989681 < (int)uVar40 && ((int)uVar40 <= (int)(uint)local_1e8)))) {
                        local_178._0_4_ = uVar40 & ((int)uVar40 >> 0x1f ^ 0xffffffffU);
                        local_178._4_4_ = (uint)local_1e8;
                        local_170 = 1;
                        if ((int)uVar40 < 1) {
                          FUN_00168a34(&DAT_004b2b38,&local_3c8);
                          local_1e8 = (void *)((ulong)local_3c8 >> 4 ^ (long)local_3c8 << 0x11 ^
                                               local_390 << 0x20 ^ local_390 & 0xffffffff);
                          FUN_0016f358(&DAT_004b2ac0,&local_1e8);
                          goto LAB_00073900;
                        }
                      }
                    }
                  }
                  pvVar2 = local_3c8;
                  if ((int)local_390 != 0) {
                    pvVar2 = (void *)(local_390 & 0xffffffff);
                  }
                  lVar28 = ((ulong)pvVar2 ^ (ulong)pvVar2 >> 0x21) * 0xafd7ed558ccd;
                  local_b0 = (((uint)((ulong)lVar28 >> 0x21) ^ (uint)lVar28) & 3) ==
                             (DAT_004e9719 & 3);
                  if ((bool)local_b0) {
                    FUN_0016edd0(&local_1e8,(double)lVar26 / dVar9,local_3c8,
                                 (void *)(local_390 & 0xffffffff),&local_298);
                    uVar40 = (uint)(char)local_1d1;
                    plVar32 = local_1e0;
                    if (-1 < (int)uVar40) {
                      plVar32 = (long *)(ulong)local_1d1;
                    }
                    if (plVar32 != (long *)0x0) {
                      std::string::operator=((string *)&local_198,(string *)&local_1e8);
                      uVar40 = (uint)local_1d1;
                    }
                    if ((uVar40 >> 7 & 1) != 0) {
                      operator_delete(local_1e8);
                    }
                  }
                  if ((ulong)(((long)DAT_004b2db0 - (long)DAT_004b2da8 >> 3) * 0x14c1bacf914c1bad) <
                      0x40) {
                    FUN_001667f0(&DAT_004b2da8,&local_1d0);
                  }
                }
LAB_00073900:
                FUN_00086284(&local_1d0);
              }
              if (((int)uVar18 <= DAT_004b2da0._4_4_) ||
                 (bVar14 = 0x5e < uVar48, uVar48 = uVar48 + 1, bVar14)) break;
            }
          }
          if (DAT_004b2da0._4_4_ < (int)uVar18) {
            bVar14 = false;
            DAT_004e971b = 1;
          }
          else {
            bVar14 = local_370 == DAT_004b00c0;
            if (bVar14) {
              FUN_0016ec44(&local_400);
              puStack_3f8 = DAT_004b2db0;
              local_400 = DAT_004b2da8;
              local_3f0[0] = DAT_004b2db8;
              DAT_004b2db0 = (undefined8 *)0x0;
              DAT_004b2db8 = 0;
              DAT_004b2da8 = (undefined8 *)0x0;
            }
            FUN_00166ae0(&DAT_004b2d90,&DAT_004e971b);
          }
        }
      }
    }
    else {
LAB_00073970:
      lStack_1c8 = 0;
      local_1d0 = (undefined *)0x0;
      local_1c0 = (undefined1 *)0x0;
      DAT_004b2d98 = 0;
      DAT_004b2da0 = 0;
      DAT_004b2d90 = (long *)0x0;
      FUN_0016ec44(&DAT_004b2da8);
      DAT_004b2da8 = (undefined8 *)0x0;
      DAT_004b2db0 = (undefined8 *)0x0;
      DAT_004b2db8 = 0;
      lStack_1a8 = 0;
      puStack_1b8 = (undefined8 *)0x0;
      local_1b0 = (long *)0x0;
      FUN_000861ac(&puStack_1b8);
      bVar14 = false;
      DAT_004e971b = 0;
    }
    if (local_308 != (void *)0x0) {
      local_300 = local_308;
      operator_delete(local_308);
    }
    puVar38 = local_400;
    puVar7 = puStack_3f8;
    if (!bVar14) goto joined_r0x000739e4;
    bVar33 = 0;
  }
  else {
    dVar52 = dVar56;
    if (((DAT_004b2b60 <= dVar56) && (0.0 < DAT_004b2b60)) && (dVar56 - DAT_004b2b60 <= 1.0)) {
      dVar49 = (double)(long)((dVar56 - DAT_004b2b60) / dVar42);
      dVar46 = 1.0;
      if (1.0 <= dVar49) {
        dVar46 = dVar49;
      }
      dVar42 = DAT_004b2b60 + dVar42 * dVar46;
      if (dVar42 <= dVar56) {
        dVar52 = dVar42;
      }
    }
    DAT_004b2b60 = dVar52;
    FUN_000448b4(&local_298);
    lVar24 = DAT_004e3180;
    if (local_298 == plVar32) {
      uVar25 = FUN_000449fc(&local_298);
      lVar26 = FUN_00044ac0(uVar25,local_238);
      iVar17 = FUN_0013bcdc();
      if ((((lVar24 == 0) && (local_20c != '\x01')) || (local_270 == 0)) || (iVar17 < 0))
      goto LAB_00072890;
      if (iVar17 == 0) {
        lStack_1c8 = 0;
        local_1d0 = (undefined *)0x0;
        local_1c0 = (undefined1 *)0x0;
        DAT_004b2d68 = 0;
        DAT_004b2d70 = 0;
        DAT_004b2d60 = (long *)0x0;
        FUN_0016ec44(&DAT_004b2d78);
        DAT_004b2d78 = (undefined8 *)0x0;
        DAT_004b2d80 = (undefined8 *)0x0;
        DAT_004b2d88 = 0;
        lStack_1a8 = 0;
        puStack_1b8 = (undefined8 *)0x0;
        local_1b0 = (long *)0x0;
        FUN_000861ac(&puStack_1b8);
        DAT_004e971a = 0;
        bVar14 = local_298 == DAT_004b00c0;
      }
      else {
        if ((DAT_004f2408 < 0x100001) || ((DAT_004f2408 & 7) != 0)) {
          if (DAT_004f2408 != 0) goto LAB_00072b10;
LAB_00072b14:
          lVar28 = FUN_00166b44(local_248,0);
          if (lVar28 == 0) {
            local_4c0 = 0;
          }
          else {
            local_4c0 = FUN_00166b44(local_240);
            iVar19 = FUN_00044b28(local_4c0,local_270);
            if (iVar19 == 0) {
              local_4c0 = 0;
            }
          }
        }
        else {
          local_4c0 = DAT_004f2408;
          uVar27 = FUN_00044b28(DAT_004f2408,local_270);
          if ((uVar27 & 1) == 0) {
LAB_00072b10:
            DAT_004f2408 = 0;
            goto LAB_00072b14;
          }
        }
        local_370 = (long *)0x0;
        local_368._0_4_ = (uint)local_368 & 0xffffff00;
        local_368 = (undefined8 *)CONCAT44(0xffffffff,(uint)local_368);
        puStack_360 = (undefined8 *)0x0;
        local_358 = 0xffffffffffffffff;
        local_350 = 0xffffffff;
        local_348 = 0;
        local_340 = 0xffffffff;
        local_338 = 0;
        local_330 = 0xffffffffffffffff;
        uStack_328 = 0xffffffffffffffff;
        local_320 = 0xffffffff;
        local_31c = 0;
        local_318 = 0;
        uStack_310 = 0;
        local_308 = (void *)0xffffffffffffffff;
        local_300 = (void *)0xffffffffffffffff;
        local_2f8 = 0;
        local_2f0 = 0xffffffffffffffff;
        local_2e8 = 0xffffffff;
        local_2e0 = 0;
        local_2d8 = 0xffffffff;
        uStack_2b8 = 0xffffffff;
        uStack_2c0 = 0xffffffff;
        uStack_2bc = 0xffffffff;
        local_2d0 = 0;
        local_2c8 = 0xffffffff;
        uStack_2c4 = 0xffffffff;
        local_2b0 = 0;
        local_2a8 = 0xffffffffffffffff;
        local_2a0 = 0xffffffff;
        std::mutex::lock();
        local_370 = DAT_004b26c8;
        local_368 = (undefined8 *)CONCAT71(local_368._1_7_,DAT_004b26d0 & DAT_004b26f8);
        local_368 = (undefined8 *)CONCAT44(DAT_004b26fc,(uint)local_368);
        puStack_360 = DAT_004b2700;
        local_358 = DAT_004b2708;
        local_350 = DAT_004b2710;
        local_348 = DAT_004b2718;
        local_340 = DAT_004b2720;
        local_338 = DAT_004b2728;
        uStack_328 = _DAT_004b2738;
        local_330 = _DAT_004b2730;
        local_320 = DAT_004b2740;
        local_31c = DAT_004b26d0 & DAT_004b275c;
        uStack_310 = DAT_004b2768;
        local_318 = DAT_004b2760;
        local_300 = _DAT_004b2778;
        local_308 = DAT_004b2770;
        local_2f8 = DAT_004b2780;
        local_2f0 = DAT_004b2788;
        local_2e8 = DAT_004b2790;
        local_2e0 = DAT_004b2798;
        local_2d8 = DAT_004b27a0;
        local_2d0 = DAT_004b27a8;
        local_2c8 = DAT_004b27b0;
        uStack_2bc = (undefined4)_DAT_004b27c0;
        uStack_2b8 = (undefined4)((ulong)_DAT_004b27c0 >> 0x20);
        uStack_2c4 = (undefined4)_DAT_004b27b8;
        uStack_2c0 = (undefined4)((ulong)_DAT_004b27b8 >> 0x20);
        local_2b0 = DAT_004b27d0;
        local_2a8 = CONCAT44(DAT_004b27e0,DAT_004b27d8);
        local_2a0 = (undefined4)DAT_004b27e8;
        std::mutex::unlock();
        if (local_1fc < 0) {
          iVar19 = 0;
        }
        else {
          iVar19 = 0;
          if ((0x100000 < local_4c0) && ((local_4c0 & 7) == 0)) {
            local_1d0 = (undefined *)((ulong)local_1d0 & 0xffffffff00000000);
            bVar16 = FUN_00166bb8(local_4c0,local_1fc,&local_1d0);
            iVar19 = (int)local_1d0;
            if ((bVar16 & (int)local_1d0 - 1U < 4) == 0) {
              iVar19 = 0;
            }
          }
        }
        local_380 = 0;
        local_378 = 0;
        uVar48 = 0;
        if (DAT_004b2c40 == (code *)0x0) {
          uVar18 = 0;
          uVar40 = 0;
        }
        else {
          lVar28 = (*DAT_004b2c40)(param_1);
          uVar18 = 0;
          uVar40 = 0;
          uVar48 = 0;
          if (lVar28 != 0) {
            uVar18 = 0;
            uVar40 = (*DAT_004b2c50)();
            uVar48 = SUB84(dVar52,0);
            local_380 = CONCAT44(uVar18,uVar40);
            local_378 = uVar48;
          }
        }
        bVar14 = false;
        if ((((uVar40 & 0x7fffffff) < 0x7f800000) && ((uVar18 & 0x7fffffff) < 0x7f800000)) &&
           ((uVar48 & 0x7fffffff) < 0x7f800000)) {
          fVar41 = DAT_004afbf4;
          if ((0x7fffffff < (uint)DAT_004afbf4 || 0x7e < (int)ABS(DAT_004afbf4) - 0x800000U >> 0x18)
              && 0x7ffffe < (int)DAT_004afbf4 - 1U) {
            fVar41 = 600.0;
          }
          fVar55 = 2000.0;
          if (fVar41 <= 2000.0) {
            fVar55 = fVar41;
          }
          if (((DAT_004b2d60 != plVar32) || (DAT_004b2d68 != lVar26)) ||
             (((int)DAT_004b2d70 != iVar17 || ((DAT_004b2d70 < 0 || (iVar17 < DAT_004b2d70._4_4_))))
             )) {
            puStack_1b8 = (undefined8 *)0x0;
            local_1c0 = (undefined1 *)0x0;
            lStack_1a8 = 0;
            local_1b0 = (undefined8 *)0x0;
            lStack_1c8 = 0;
            local_1d0 = (undefined *)0x0;
            DAT_004b2d68 = 0;
            DAT_004b2d70 = 0;
            DAT_004b2d60 = (long *)0x0;
            FUN_0016ec44(&DAT_004b2d78);
            DAT_004b2d80 = local_1b0;
            DAT_004b2d78 = puStack_1b8;
            DAT_004b2d88 = lStack_1a8;
            lStack_1a8 = 0;
            local_1b0 = (long *)0x0;
            puStack_1b8 = (undefined8 *)0x0;
            FUN_000861ac(&puStack_1b8);
            DAT_004b2d60 = plVar32;
            DAT_004b2d70 = CONCAT44(DAT_004b2d70._4_4_,iVar17);
            DAT_004b2d68 = lVar26;
            FUN_00166734(&DAT_004b2d78,iVar17);
          }
          lVar28 = std::chrono::steady_clock::now();
          uVar43 = _UNK_0044cf38;
          uVar25 = _DAT_0044cf30;
          if (DAT_004b2d70._4_4_ < iVar17) {
            dVar42 = (double)lVar28 / dVar9 + DAT_0044ce58;
            uVar48 = 0;
            while( true ) {
              lVar28 = std::chrono::steady_clock::now();
              iVar20 = DAT_004b2d70._4_4_;
              if (dVar42 <= (double)lVar28 / dVar9) break;
              DAT_004b2d70 = CONCAT44(DAT_004b2d70._4_4_ + 1,(int)DAT_004b2d70);
              local_384 = 0;
              local_390 = 0;
              uVar27 = FUN_0013bd48(lVar26,iVar20,&local_384,&local_390);
              if ((uVar27 & 1) == 0) {
                lStack_1c8 = 0;
                local_1d0 = (undefined *)0x0;
                local_1c0 = (undefined1 *)0x0;
                DAT_004b2d68 = 0;
                DAT_004b2d70 = 0;
                DAT_004b2d60 = (long *)0x0;
                FUN_0016ec44(&DAT_004b2d78);
                goto LAB_000728c0;
              }
              if ((((local_384 != 0) && (0x100000 < local_390)) && ((local_390 & 7) == 0)) &&
                 ((local_390 != local_4c0 &&
                  (iVar20 = FUN_00044b28(local_390,local_270), iVar20 != 0)))) {
                if ((local_20c == '\x01') && (-1 < (int)local_214)) {
                  local_1d0 = (undefined *)0x0;
                  iVar20 = FUN_000d27d0(local_390 + local_214,&local_1d0,8);
                  puVar29 = local_1d0;
                  if (iVar20 == 0) {
                    puVar29 = (undefined *)0x0;
                  }
                }
                else {
                  puVar29 = (undefined *)FUN_00166b44(lVar24);
                }
                uVar18 = local_384;
                uVar27 = local_390;
                local_16c = 0;
                local_168 = 0;
                lStack_1c8 = 0;
                local_1d0 = (undefined *)0x0;
                puStack_1b8 = (undefined8 *)0x0;
                local_1c0 = (undefined1 *)0x0;
                lStack_1a8 = 0;
                local_1b0 = (long *)0x0;
                local_1a0 = local_1a0 & 0xffffffffffff0000;
                plStack_190 = (long *)0x0;
                local_198 = (void *)0x0;
                uStack_180 = 0;
                local_188 = (long *)0x0;
                local_178._4_4_ = 0;
                local_170 = 0;
                uStack_17f = 0;
                local_178._0_4_ = 0;
                local_158 = 0;
                uStack_150 = 0;
                local_160 = 0;
                local_148 = 0;
                plStack_138 = (long *)0x0;
                local_140 = (long *)0x0;
                local_128 = (void *)0x0;
                local_130 = 0;
                lStack_118 = 0;
                uStack_120 = 0;
                uStack_108 = 0;
                uStack_110 = 0;
                uStack_f8 = 0;
                local_100 = 0;
                uStack_e8 = 0;
                uStack_f0 = 0;
                local_e0 = 0;
                uStack_d4 = 0;
                uStack_dc = 0;
                local_d7 = 0;
                uStack_c4 = uVar43;
                local_cc = uVar25;
                local_bc = 0;
                local_b8 = 0;
                local_b0 = 0;
                local_1e8 = (void *)CONCAT17(local_1e8._7_1_,0xc743f907000000);
                local_1e8 = (void *)CONCAT44(local_1e8._4_4_,0x7c45603);
                FUN_00168890(&local_3b0,&local_1e8);
                uVar27 = FUN_00166c40(fVar55,param_1,uVar27,puVar29,uVar18,0,&local_3b0,&local_380,
                                      &local_1d0);
                FUN_0016741c(&local_3b0);
                if ((uVar27 & 1) != 0) {
                  if (-1 < local_1fc) {
                    local_1e8 = (void *)((ulong)local_1e8 & 0xffffffff00000000);
                    iVar21 = FUN_00166bb8(local_390,local_1fc,&local_1e8);
                    iVar20 = 0;
                    if ((uint)local_1e8 - 1 < 4) {
                      iVar20 = iVar21;
                    }
                    if (iVar20 == 1) {
                      local_16c = (uint)local_1e8;
                      local_168 = iVar19 != 0 && (uint)local_1e8 == iVar19;
                    }
                  }
                  if ((-1 < (int)local_204) && (-1 < local_200)) {
                    local_1e8 = (void *)((ulong)local_1e8 & 0xffffffff00000000);
                    uVar27 = FUN_000d27d0(local_390 + local_204,&local_1e8,4);
                    if ((uVar27 & 1) != 0) {
                      uVar18 = (uint)local_1e8;
                      local_1e8 = (void *)((ulong)local_1e8 & 0xffffffff00000000);
                      uVar27 = FUN_000d27d0(local_390 + (long)local_200,&local_1e8,4);
                      if (((((uVar27 & 1) != 0) && (0xff67697f < (uint)local_1e8 - 0x989681)) &&
                          (-0x989681 < (int)uVar18)) && ((int)uVar18 <= (int)(uint)local_1e8)) {
                        local_178._0_4_ = uVar18 & ((int)uVar18 >> 0x1f ^ 0xffffffffU);
                        local_178._4_4_ = (uint)local_1e8;
                        local_170 = 1;
                        if ((int)uVar18 < 1) {
                          FUN_00168a34(&DAT_004b2b38,&local_390);
                          goto LAB_000733c4;
                        }
                      }
                    }
                  }
                  uVar27 = local_390;
                  if (local_384 != 0) {
                    uVar27 = (ulong)local_384;
                  }
                  lVar28 = (uVar27 ^ uVar27 >> 0x21) * 0xafd7ed558ccd;
                  uVar18 = ((uint)((ulong)lVar28 >> 0x21) ^ (uint)lVar28) & 3;
                  uVar40 = (uint)DAT_004e9719;
                  local_b0 = uVar18 == (uVar40 & 3);
                  if ((((bool)local_b0) && (local_370 == plVar32)) && ((char)local_368 == '\x01')) {
                    FUN_00167450(&local_1e8,local_390,&local_370);
                    plVar31 = local_1e0;
                    if (-1 < (char)local_1d1) {
                      plVar31 = (long *)(ulong)local_1d1;
                    }
                    if (plVar31 != (long *)0x0) {
                      std::string::operator=((string *)&local_198,(string *)&local_1e8);
                    }
                    local_394 = 0;
                    local_3b0 = (long *)0x0;
                    plStack_3a8 = (long *)0x0;
                    local_3a0 = 0;
                    local_3c8 = (void *)0x0;
                    uStack_3c0 = 0;
                    local_3b8 = 0;
                    iVar20 = FUN_001675e8(local_390,&local_370,&local_394,&local_3b0,&local_3c8);
                    if (iVar20 == 0) {
                      if (local_3b8 < 0) {
                        operator_delete(local_3c8);
                      }
                    }
                    else {
                      local_148 = local_394;
                      if ((long)local_130 < 0) {
                        operator_delete(local_140);
                      }
                      plStack_138 = plStack_3a8;
                      local_140 = local_3b0;
                      local_130 = local_3a0;
                      local_3a0 = local_3a0 & 0xffffffffffffff;
                      local_3b0 = (long *)((ulong)local_3b0 & 0xffffffffffffff00);
                      if (lStack_118 < 0) {
                        operator_delete(local_128);
                      }
                      uStack_120 = uStack_3c0;
                      local_128 = local_3c8;
                      lStack_118 = local_3b8;
                    }
                    if ((long)local_3a0 < 0) {
                      operator_delete(local_3b0);
                    }
                    if ((char)local_1d1 < '\0') {
                      operator_delete(local_1e8);
                    }
                  }
                  if ((DAT_004afc0c != '\x01') || ((local_168 & 1) == 0)) {
                    if (((uVar18 == (uVar40 & 3)) && ((local_168 & 1) == 0)) &&
                       (((DAT_004afbcd & 1) != 0 || ((DAT_004afbd7 & 1) != 0)))) {
                      FUN_001678fc(local_390,local_384,&local_370,&uStack_110,&uStack_f8,
                                   DAT_004afbd7 & 1);
                    }
                    if ((ulong)(((long)DAT_004b2d80 - (long)DAT_004b2d78 >> 3) * 0x14c1bacf914c1bad)
                        < 0x80) {
                      FUN_001667f0(&DAT_004b2d78,&local_1d0);
                    }
                  }
                }
LAB_000733c4:
                FUN_00086284(&local_1d0);
              }
              if ((iVar17 <= DAT_004b2d70._4_4_) ||
                 (bVar14 = 0x5e < uVar48, uVar48 = uVar48 + 1, bVar14)) break;
            }
          }
          if (DAT_004b2d70._4_4_ < iVar17) {
            bVar14 = false;
            DAT_004e971a = 1;
          }
          else {
            bVar14 = local_298 == DAT_004b00c0;
            if (bVar14) {
              FUN_0016ec44(&local_3e0);
              puStack_3d8 = DAT_004b2d80;
              local_3e0 = DAT_004b2d78;
              local_3d0 = DAT_004b2d88;
              DAT_004b2d80 = (undefined8 *)0x0;
              DAT_004b2d88 = 0;
              DAT_004b2d78 = (undefined8 *)0x0;
            }
            FUN_00166ae0(&DAT_004b2d60,&DAT_004e971a);
          }
        }
      }
    }
    else {
LAB_00072890:
      lStack_1c8 = 0;
      local_1d0 = (undefined *)0x0;
      local_1c0 = (undefined1 *)0x0;
      DAT_004b2d68 = 0;
      DAT_004b2d70 = 0;
      DAT_004b2d60 = (long *)0x0;
      FUN_0016ec44(&DAT_004b2d78);
LAB_000728c0:
      DAT_004b2d88 = 0;
      DAT_004b2d80 = (undefined8 *)0x0;
      DAT_004b2d78 = (undefined8 *)0x0;
      lStack_1a8 = 0;
      puStack_1b8 = (undefined8 *)0x0;
      local_1b0 = (long *)0x0;
      FUN_000861ac(&puStack_1b8);
      bVar14 = false;
      DAT_004e971a = 0;
    }
    if (local_230 != (void *)0x0) {
      local_228 = local_230;
      operator_delete(local_230);
    }
    puVar7 = local_3e0;
    uVar48 = SUB84(dVar52,0);
    puVar38 = puStack_3d8;
    if (!bVar14) {
      while (puVar38 != puVar7) {
        FUN_00086210(&local_3d0,puVar38 + -0x25);
        puVar38 = puVar38 + -0x25;
      }
      puStack_3d8 = puVar7;
      goto LAB_0007292c;
    }
    bVar16 = 0;
    if ((bVar34 & 1) != 0) goto LAB_00072934;
LAB_00073a08:
    bVar33 = 1;
  }
  lVar24 = DAT_004b2dc0;
  if (DAT_004afbd0 == '\x01') {
    FUN_0022a57c();
  }
  else {
    lVar26 = DAT_004b2dc8;
    if (DAT_004b2dc0 == DAT_004b2dc8) {
      if (DAT_004b2df0 == 0 && DAT_004b2e18 == 0) goto LAB_00073a90;
    }
    else {
      do {
        lVar26 = lVar26 + -0x70;
        FUN_0016f984(&DAT_004b2dd0,lVar26);
      } while (lVar26 != lVar24);
    }
    DAT_004b2dc8 = lVar24;
    FUN_0016f9c8(&DAT_004b2dd8);
    FUN_00087e0c(&DAT_004b2e00);
  }
LAB_00073a90:
  plVar32 = (long *)DAT_004b2b48;
  if (DAT_004b2b50 != 0) {
    while (plVar32 != (long *)0x0) {
      if (plVar32[2] == 0) {
LAB_00073ad8:
        plVar32 = (long *)FUN_00168b54(&DAT_004b2b38);
      }
      else {
        dVar42 = dVar56 - (double)plVar32[0x1b];
        bVar14 = false;
        bVar15 = false;
        bVar10 = false;
        if (0.0 < (double)plVar32[0x1b]) {
          bVar14 = false;
          bVar15 = false;
          bVar10 = true;
          if (!NAN(dVar42)) {
            bVar14 = dVar42 < 1.5;
            bVar15 = dVar42 == 1.5;
            bVar10 = false;
          }
        }
        if (!bVar15 && bVar14 == bVar10) goto LAB_00073ad8;
        plVar32 = (long *)*plVar32;
      }
    }
    while (0x180 < DAT_004b2b50) {
      FUN_00168b54(&DAT_004b2b38,DAT_004b2b48);
    }
  }
  if (((bVar11 | bVar34 | bVar3 & bVar4 ^ 0xff) & 1) == 0) goto LAB_00074420;
  FUN_0003e7e8(&local_3b0);
  plVar32 = local_3b0;
  local_370 = (long *)0x0;
  local_368 = (undefined8 *)0x0;
  puStack_360 = (undefined8 *)0x0;
  if (local_3b0 == (long *)0x0) {
    lVar24 = 0;
  }
  else {
    lVar24 = (local_3b0[1] - *local_3b0 >> 3) * 0x14c1bacf914c1bad;
  }
  FUN_00166734(&local_370,
               lVar24 + ((long)puStack_3d8 - (long)local_3e0 >> 3) * 0x14c1bacf914c1bad +
               ((long)puStack_3f8 - (long)local_400 >> 3) * 0x14c1bacf914c1bad);
  if ((bVar16 & bVar11) == 1) {
    if ((DAT_004e971a & 1) == 0) {
      bVar14 = dVar56 - DAT_004b2b70 <= DAT_0029bfa0 && 0.0 < DAT_004b2b70;
    }
    else {
      bVar14 = true;
    }
  }
  else {
    bVar14 = false;
  }
  if ((bVar34 & bVar33) == 1) {
    bVar15 = (DAT_004e971b & 1) != 0 || dVar56 - DAT_004b2b78 <= DAT_0029bfa0 && 0.0 < DAT_004b2b78;
  }
  else {
    bVar15 = false;
  }
  if (plVar32 != (long *)0x0) {
    plVar31 = (long *)plVar32[1];
    if ((long *)*plVar32 != plVar31) {
      plVar32 = (long *)*plVar32 + 0x10;
      do {
        puVar38 = local_368;
        plVar36 = plVar32 + -0x10;
        if ((char)plVar32[0xe] == '\x01') {
          if ((bVar4 & (bVar33 | bVar34 ^ 1) & 1) != 0) {
            if ((bVar34 & 1) == 0) goto LAB_00073d0c;
            lVar24 = FUN_00196398(&local_460,plVar32 + -2);
            if (lVar24 == 0) {
              if (*plVar32 == 0) {
                if (bVar15) goto LAB_00073d0c;
              }
              else {
                lVar24 = FUN_0016fc48(&local_430,plVar32);
                if ((bool)(lVar24 == 0 & bVar15)) {
LAB_00073d0c:
                  puVar38 = local_368;
                  if (local_368 == puStack_360) goto LAB_00073d30;
                  FUN_0016fb40(local_368,plVar36);
                  goto LAB_00073d24;
                }
              }
            }
          }
        }
        else {
          if ((char)plVar32[0xe] == '\0') {
            if ((bVar3 & (bVar11 ^ 1 | bVar14) & 1) == 0) goto LAB_00073d3c;
            if (local_368 == puStack_360) goto LAB_00073d30;
            FUN_0016fb40(local_368,plVar36);
          }
          else {
            if (local_368 == puStack_360) {
LAB_00073d30:
              FUN_0016fa2c(&local_370,plVar36);
              goto LAB_00073d3c;
            }
            FUN_0016fb40(local_368,plVar36);
          }
LAB_00073d24:
          local_368 = puVar38 + 0x25;
        }
LAB_00073d3c:
        plVar36 = plVar32 + 0x15;
        plVar32 = plVar32 + 0x25;
      } while (plVar36 != plVar31);
    }
  }
  puVar38 = puStack_3d8;
  if ((bVar11 & 1) != 0) {
    puVar7 = local_3e0;
    puVar8 = local_3e0;
    if (bVar16 == 0) {
      for (; puVar7 != puVar38; puVar7 = puVar7 + 0x25) {
        if (((*(byte *)(puVar7 + 0x24) & 1) == 0) && (local_3b0 != (long *)0x0)) {
          if ((char *)*local_3b0 != (char *)local_3b0[1]) {
            pcVar37 = (char *)*local_3b0 + 0xf0;
            do {
              if ((puVar7[0x10] == 0) || (*(long *)(pcVar37 + -0x70) == 0)) {
                bVar14 = puVar7[0xe] == *(long *)(pcVar37 + -0x80);
              }
              else {
                bVar14 = puVar7[0x10] == *(long *)(pcVar37 + -0x70);
              }
              if (bVar14 && *pcVar37 == '\0') {
                std::string::operator=((string *)(puVar7 + 7),(string *)(pcVar37 + -0xb8));
                *(undefined4 *)(puVar7 + 0x11) = *(undefined4 *)(pcVar37 + -0x68);
                std::string::operator=((string *)(puVar7 + 0x12),(string *)(pcVar37 + -0x60));
                std::string::operator=((string *)(puVar7 + 0x15),(string *)(pcVar37 + -0x48));
                std::string::operator=((string *)(puVar7 + 0x18),(string *)(pcVar37 + -0x30));
                std::string::operator=((string *)(puVar7 + 0x1b),(string *)(pcVar37 + -0x18));
                break;
              }
              pcVar1 = pcVar37 + 0x38;
              pcVar37 = pcVar37 + 0x128;
            } while (pcVar1 != (char *)local_3b0[1]);
          }
        }
        if (local_368 < puStack_360) {
          uVar43 = puVar7[1];
          uVar25 = *puVar7;
          uVar47 = puVar7[3];
          uVar30 = puVar7[2];
          uVar51 = puVar7[5];
          uVar50 = puVar7[4];
          *(undefined2 *)(local_368 + 6) = *(undefined2 *)(puVar7 + 6);
          local_368[3] = uVar47;
          local_368[2] = uVar30;
          local_368[5] = uVar51;
          local_368[4] = uVar50;
          local_368[1] = uVar43;
          *local_368 = uVar25;
          uVar43 = puVar7[8];
          uVar25 = puVar7[7];
          local_368[9] = puVar7[9];
          local_368[8] = uVar43;
          local_368[7] = uVar25;
          puVar7[8] = 0;
          puVar7[9] = 0;
          puVar7[7] = 0;
          uVar43 = puVar7[0xb];
          uVar25 = puVar7[10];
          uVar47 = puVar7[0xd];
          uVar30 = puVar7[0xc];
          uVar51 = puVar7[0xf];
          uVar50 = puVar7[0xe];
          uVar53 = *(undefined8 *)((long)puVar7 + 0x7c);
          *(undefined8 *)((long)local_368 + 0x84) = *(undefined8 *)((long)puVar7 + 0x84);
          *(undefined8 *)((long)local_368 + 0x7c) = uVar53;
          local_368[0xd] = uVar47;
          local_368[0xc] = uVar30;
          local_368[0xf] = uVar51;
          local_368[0xe] = uVar50;
          local_368[0xb] = uVar43;
          local_368[10] = uVar25;
          uVar43 = puVar7[0x13];
          uVar25 = puVar7[0x12];
          local_368[0x14] = puVar7[0x14];
          local_368[0x13] = uVar43;
          local_368[0x12] = uVar25;
          puVar7[0x12] = 0;
          puVar7[0x13] = 0;
          puVar7[0x14] = 0;
          uVar43 = puVar7[0x16];
          uVar25 = puVar7[0x15];
          local_368[0x17] = puVar7[0x17];
          local_368[0x16] = uVar43;
          local_368[0x15] = uVar25;
          puVar7[0x15] = 0;
          puVar7[0x16] = 0;
          puVar7[0x17] = 0;
          uVar43 = puVar7[0x19];
          uVar25 = puVar7[0x18];
          local_368[0x1a] = puVar7[0x1a];
          local_368[0x19] = uVar43;
          local_368[0x18] = uVar25;
          puVar7[0x18] = 0;
          puVar7[0x19] = 0;
          puVar7[0x1a] = 0;
          uVar43 = puVar7[0x1c];
          uVar25 = puVar7[0x1b];
          local_368[0x1d] = puVar7[0x1d];
          local_368[0x1c] = uVar43;
          local_368[0x1b] = uVar25;
          puVar7[0x1b] = 0;
          puVar7[0x1c] = 0;
          puVar7[0x1d] = 0;
          uVar43 = puVar7[0x1f];
          uVar25 = puVar7[0x1e];
          uVar47 = puVar7[0x21];
          uVar30 = puVar7[0x20];
          uVar51 = puVar7[0x23];
          uVar50 = puVar7[0x22];
          *(undefined1 *)(local_368 + 0x24) = *(undefined1 *)(puVar7 + 0x24);
          local_368[0x21] = uVar47;
          local_368[0x20] = uVar30;
          local_368[0x23] = uVar51;
          local_368[0x22] = uVar50;
          local_368[0x1f] = uVar43;
          local_368[0x1e] = uVar25;
          local_368 = local_368 + 0x25;
        }
        else {
          FUN_0016fcfc(&local_370,puVar7);
        }
        puVar8 = puStack_3d8;
      }
      dVar42 = 0.0;
      if (local_3e0 != puVar8) {
        dVar42 = dVar56;
      }
    }
    else {
      dVar42 = 0.0;
      if (bVar14 != false) goto LAB_00073f34;
    }
    DAT_004b2b70 = dVar42;
  }
LAB_00073f34:
  puVar38 = puStack_3f8;
  if ((bVar34 & 1) != 0) {
    puVar7 = local_400;
    puVar8 = local_400;
    if (bVar33 == 0) {
      for (; puVar7 != puVar38; puVar7 = puVar7 + 0x25) {
        if (((*(byte *)(puVar7 + 0x24) & 1) == 0) && (local_3b0 != (long *)0x0)) {
          lVar24 = *local_3b0;
          if (lVar24 != local_3b0[1]) {
            do {
              if ((puVar7[0x10] == 0) || (*(long *)(lVar24 + 0x80) == 0)) {
                bVar14 = puVar7[0xe] == *(long *)(lVar24 + 0x70);
              }
              else {
                bVar14 = puVar7[0x10] == *(long *)(lVar24 + 0x80);
              }
              if (bVar14 && *(char *)(lVar24 + 0xf0) == '\x01') {
                std::string::operator=((string *)(puVar7 + 7),(string *)(lVar24 + 0x38));
                break;
              }
              lVar24 = lVar24 + 0x128;
            } while (lVar24 != local_3b0[1]);
          }
        }
        if (local_368 < puStack_360) {
          uVar43 = puVar7[1];
          uVar25 = *puVar7;
          uVar47 = puVar7[3];
          uVar30 = puVar7[2];
          uVar51 = puVar7[5];
          uVar50 = puVar7[4];
          *(undefined2 *)(local_368 + 6) = *(undefined2 *)(puVar7 + 6);
          local_368[3] = uVar47;
          local_368[2] = uVar30;
          local_368[5] = uVar51;
          local_368[4] = uVar50;
          local_368[1] = uVar43;
          *local_368 = uVar25;
          uVar43 = puVar7[8];
          uVar25 = puVar7[7];
          local_368[9] = puVar7[9];
          local_368[8] = uVar43;
          local_368[7] = uVar25;
          puVar7[8] = 0;
          puVar7[9] = 0;
          puVar7[7] = 0;
          uVar43 = puVar7[0xb];
          uVar25 = puVar7[10];
          uVar47 = puVar7[0xd];
          uVar30 = puVar7[0xc];
          uVar51 = puVar7[0xf];
          uVar50 = puVar7[0xe];
          uVar53 = *(undefined8 *)((long)puVar7 + 0x7c);
          *(undefined8 *)((long)local_368 + 0x84) = *(undefined8 *)((long)puVar7 + 0x84);
          *(undefined8 *)((long)local_368 + 0x7c) = uVar53;
          local_368[0xd] = uVar47;
          local_368[0xc] = uVar30;
          local_368[0xf] = uVar51;
          local_368[0xe] = uVar50;
          local_368[0xb] = uVar43;
          local_368[10] = uVar25;
          uVar43 = puVar7[0x13];
          uVar25 = puVar7[0x12];
          local_368[0x14] = puVar7[0x14];
          local_368[0x13] = uVar43;
          local_368[0x12] = uVar25;
          puVar7[0x12] = 0;
          puVar7[0x13] = 0;
          puVar7[0x14] = 0;
          uVar43 = puVar7[0x16];
          uVar25 = puVar7[0x15];
          local_368[0x17] = puVar7[0x17];
          local_368[0x16] = uVar43;
          local_368[0x15] = uVar25;
          puVar7[0x15] = 0;
          puVar7[0x16] = 0;
          puVar7[0x17] = 0;
          uVar43 = puVar7[0x19];
          uVar25 = puVar7[0x18];
          local_368[0x1a] = puVar7[0x1a];
          local_368[0x19] = uVar43;
          local_368[0x18] = uVar25;
          puVar7[0x18] = 0;
          puVar7[0x19] = 0;
          puVar7[0x1a] = 0;
          uVar43 = puVar7[0x1c];
          uVar25 = puVar7[0x1b];
          local_368[0x1d] = puVar7[0x1d];
          local_368[0x1c] = uVar43;
          local_368[0x1b] = uVar25;
          puVar7[0x1b] = 0;
          puVar7[0x1c] = 0;
          puVar7[0x1d] = 0;
          uVar43 = puVar7[0x1f];
          uVar25 = puVar7[0x1e];
          uVar47 = puVar7[0x21];
          uVar30 = puVar7[0x20];
          uVar51 = puVar7[0x23];
          uVar50 = puVar7[0x22];
          *(undefined1 *)(local_368 + 0x24) = *(undefined1 *)(puVar7 + 0x24);
          local_368[0x21] = uVar47;
          local_368[0x20] = uVar30;
          local_368[0x23] = uVar51;
          local_368[0x22] = uVar50;
          local_368[0x1f] = uVar43;
          local_368[0x1e] = uVar25;
          local_368 = local_368 + 0x25;
        }
        else {
          FUN_0016fcfc(&local_370,puVar7);
        }
        puVar8 = puStack_3f8;
      }
      dVar42 = 0.0;
      if (local_400 != puVar8) {
        dVar42 = dVar56;
      }
    }
    else {
      dVar42 = 0.0;
      if (bVar15) goto LAB_000740d8;
    }
    DAT_004b2b78 = dVar42;
  }
LAB_000740d8:
  puVar38 = local_368;
  plVar32 = local_370;
  local_178 = (double)CONCAT44(local_178._4_4_,(uint)local_178);
  if ((lVar23 == DAT_004aff08) &&
     (local_178 = (double)CONCAT44(local_178._4_4_,(uint)local_178), plVar6 == DAT_004b00c0)) {
    local_480 = local_370;
    puStack_470 = puStack_360;
    puStack_478 = local_368;
    local_368 = (undefined8 *)0x0;
    puStack_360 = (undefined8 *)0x0;
    local_370 = (long *)0x0;
    lVar24 = std::chrono::steady_clock::now();
    std::recursive_mutex::lock();
    do {
      uVar27 = DAT_004e2a20 + 1;
      cVar5 = '\x01';
      bVar14 = (bool)ExclusiveMonitorPass(0x4e2a20,0x10);
      if (bVar14) {
        cVar5 = ExclusiveMonitorsStatus();
        DAT_004e2a20 = uVar27;
      }
    } while (cVar5 != '\0');
    DAT_004e2a28 = uVar27;
    std::recursive_mutex::unlock();
    plVar31 = operator_new(0x30);
    plVar36 = plVar31 + 1;
    *plVar36 = 0;
    plVar31[2] = 0;
    *plVar31 = (long)&DAT_004a10f8;
    plVar35 = plVar31 + 3;
    plVar31[4] = (long)puStack_478;
    *plVar35 = (long)local_480;
    plVar31[5] = (long)puStack_470;
    local_480 = (long *)0x0;
    puStack_478 = (undefined8 *)0x0;
    puStack_470 = (undefined8 *)0x0;
    local_298 = plVar35;
    local_290 = plVar31;
    FUN_00170164(&local_1e8,&DAT_004b22b0);
    if (DAT_004e9a40 != -1) {
      FUN_00294f00();
    }
    lVar26 = DAT_004e9a38;
    if (DAT_004e9a38 == 0) {
      lStack_1c8 = plVar31[4];
      local_1d0 = (undefined *)plVar31[3];
      local_1c0 = (undefined1 *)plVar31[5];
      plVar31[4] = 0;
      plVar31[5] = 0;
      *plVar35 = 0;
      FUN_000863ec((double)lVar24 / dVar9,&local_1d0,plVar6,lVar23,uVar27);
      FUN_000861ac(&local_1d0);
    }
    else {
      local_1d0 = PTR___NSConcreteStackBlock_004a01f8;
      lStack_1c8 = DAT_0044ce68;
      local_1c0 = &LAB_0016fec0;
      puStack_1b8 = (undefined8 *)&DAT_004a10b8;
      local_1b0 = plVar6;
      lStack_1a8 = lVar23;
      local_198 = local_1e8;
      plStack_190 = local_1e0;
      if (local_1e0 != (long *)0x0) {
        plVar6 = local_1e0 + 1;
        do {
          cVar5 = '\x01';
          bVar14 = (bool)ExclusiveMonitorPass(plVar6,0x10);
          if (bVar14) {
            *plVar6 = *plVar6 + 1;
            cVar5 = ExclusiveMonitorsStatus();
          }
        } while (cVar5 != '\0');
      }
      uStack_180 = SUB81(plVar31,0);
      uStack_17f = (undefined7)((ulong)plVar31 >> 8);
      do {
        cVar5 = '\x01';
        bVar14 = (bool)ExclusiveMonitorPass(plVar36,0x10);
        if (bVar14) {
          *plVar36 = *plVar36 + 1;
          cVar5 = ExclusiveMonitorsStatus();
        }
      } while (cVar5 != '\0');
      local_1a0 = uVar27;
      local_188 = plVar35;
      local_178 = (double)lVar24 / dVar9;
      _dispatch_async(lVar26,&local_1d0);
      plVar6 = (long *)CONCAT71(uStack_17f,uStack_180);
      if (plVar6 != (long *)0x0) {
        plVar31 = plVar6 + 1;
        do {
          lVar23 = *plVar31;
          cVar5 = '\x01';
          bVar14 = (bool)ExclusiveMonitorPass(plVar31,0x10);
          if (bVar14) {
            *plVar31 = lVar23 + -1;
            cVar5 = ExclusiveMonitorsStatus();
          }
        } while (cVar5 != '\0');
        if (lVar23 == 0) {
          (**(code **)(*plVar6 + 0x10))(plVar6);
          std::__shared_weak_count::__release_weak();
        }
      }
      if (plStack_190 != (long *)0x0) {
        plVar6 = plStack_190 + 1;
        do {
          lVar23 = *plVar6;
          cVar5 = '\x01';
          bVar14 = (bool)ExclusiveMonitorPass(plVar6,0x10);
          if (bVar14) {
            *plVar6 = lVar23 + -1;
            cVar5 = ExclusiveMonitorsStatus();
          }
        } while (cVar5 != '\0');
        if (lVar23 == 0) {
          (**(code **)(*plStack_190 + 0x10))(plStack_190);
          std::__shared_weak_count::__release_weak();
        }
      }
    }
    if (local_1e0 != (long *)0x0) {
      plVar6 = local_1e0 + 1;
      do {
        lVar23 = *plVar6;
        cVar5 = '\x01';
        bVar14 = (bool)ExclusiveMonitorPass(plVar6,0x10);
        if (bVar14) {
          *plVar6 = lVar23 + -1;
          cVar5 = ExclusiveMonitorsStatus();
        }
      } while (cVar5 != '\0');
      if (lVar23 == 0) {
        (**(code **)(*local_1e0 + 0x10))(local_1e0);
        std::__shared_weak_count::__release_weak();
      }
    }
    if (local_290 != (long *)0x0) {
      plVar6 = local_290 + 1;
      do {
        lVar23 = *plVar6;
        cVar5 = '\x01';
        bVar14 = (bool)ExclusiveMonitorPass(plVar6,0x10);
        if (bVar14) {
          *plVar6 = lVar23 + -1;
          cVar5 = ExclusiveMonitorsStatus();
        }
      } while (cVar5 != '\0');
      if (lVar23 == 0) {
        (**(code **)(*local_290 + 0x10))(local_290);
        std::__shared_weak_count::__release_weak();
      }
    }
    FUN_000861ac(&local_480);
    FUN_0007ad44(dVar54,1,((long)puVar38 - (long)plVar32 >> 3) * 0x14c1bacf914c1bad,1);
  }
  FUN_000861ac(&local_370);
  if (plStack_3a8 != (long *)0x0) {
    plVar6 = plStack_3a8 + 1;
    do {
      lVar23 = *plVar6;
      cVar5 = '\x01';
      bVar14 = (bool)ExclusiveMonitorPass(plVar6,0x10);
      if (bVar14) {
        *plVar6 = lVar23 + -1;
        cVar5 = ExclusiveMonitorsStatus();
      }
    } while (cVar5 != '\0');
    if (lVar23 == 0) {
      (**(code **)(*plStack_3a8 + 0x10))(plStack_3a8);
      std::__shared_weak_count::__release_weak();
    }
  }
LAB_00074420:
  FUN_00143044(&local_460);
  FUN_00197930(&local_430);
  FUN_000861ac(&local_400);
  FUN_000861ac(&local_3e0);
  return;
}



/* FUN_0017332c at 0017332c */

void FUN_0017332c(float param_1,undefined4 param_2,undefined8 param_3,undefined8 param_4,
                 char *param_5)

{
  float fVar1;
  
  if ((param_5 != (char *)0x0) && (*param_5 != '\0')) {
    fVar1 = (float)FUN_00174208(param_5);
    FUN_00174308(param_1 + fVar1 * -0.5,param_2,param_3,param_4,param_5);
    return;
  }
  return;
}



/* FUN_0018c8dc at 0018c8dc */

void FUN_0018c8dc(float param_1,float param_2,undefined8 param_3,undefined8 param_4,char *param_5)

{
  long lVar1;
  float fVar2;
  float fVar3;
  int iVar4;
  float fVar5;
  float local_60;
  float fStack_5c;
  float local_58;
  float fStack_54;
  
  lVar1 = FUN_00100c88();
  if (((param_5 != (char *)0x0) && (lVar1 != 0)) && (*param_5 != '\0')) {
    fVar5 = (float)(int)param_1;
    fStack_54 = (float)(int)param_2;
    fVar2 = DAT_004afc00;
    if (0x7f7fffff < (uint)ABS(DAT_004afc00)) {
      fVar2 = 7.25;
    }
    fVar3 = 5.0;
    if (5.0 <= fVar2) {
      fVar3 = fVar2;
    }
    fVar2 = 14.0;
    if (fVar3 <= 14.0) {
      fVar2 = fVar3;
    }
    fVar3 = 6.0;
    if (6.0 <= fVar2 * DAT_0044d2c8) {
      fVar3 = fVar2 * DAT_0044d2c8;
    }
    fVar2 = 14.0;
    if (fVar3 <= 14.0) {
      fVar2 = fVar3;
    }
    iVar4 = (int)fVar2;
    local_60 = fVar5 + 1.0;
    fVar2 = fStack_54 + 1.0;
    fStack_5c = fVar2;
    local_58 = fVar5;
    FUN_0027bbc0(iVar4,0,param_3,lVar1,&local_60,0xdc000000,param_5,0,0);
    local_60 = fVar5 + -1.0;
    fStack_5c = fVar2;
    FUN_0027bbc0(iVar4,0,param_3,lVar1,&local_60,0xdc000000,param_5,0,0);
    FUN_0027bbc0(iVar4,0,param_3,lVar1,&local_58,param_4,param_5,0,0);
  }
  return;
}



/* FUN_00279198 at 00279198 */

void FUN_00279198(int *param_1)

{
  int iVar1;
  int iVar2;
  undefined8 *puVar3;
  long lVar4;
  long lVar5;
  undefined8 uVar6;
  
  iVar1 = param_1[0x16];
  iVar2 = (int)((long)iVar1 + -1);
  param_1[0x16] = iVar2;
  if (iVar2 == 0) {
    puVar3 = (undefined8 *)(*(long *)(param_1 + 0xe) + 0x1c);
  }
  else {
    puVar3 = (undefined8 *)(*(long *)(param_1 + 0x18) + ((long)iVar1 + -1) * 0x10 + -0x10);
  }
  uVar6 = *puVar3;
  *(undefined8 *)(param_1 + 0x24) = puVar3[1];
  *(undefined8 *)(param_1 + 0x22) = uVar6;
  iVar1 = *param_1;
  lVar4 = *(long *)(param_1 + 2) + (long)iVar1 * 0x38;
  if (*(int *)(lVar4 + -0x18) == 0) {
    if (((1 < iVar1) &&
        (((*(long *)(param_1 + 0x22) == *(long *)(lVar4 + -0x70) &&
          *(long *)(param_1 + 0x24) == *(long *)(lVar4 + -0x68)) &&
         *(long *)(param_1 + 0x26) == *(long *)(lVar4 + -0x60)) &&
         param_1[0x28] == *(int *)(lVar4 + -0x58))) && (*(long *)(lVar4 + -0x48) == 0)) {
      *param_1 = iVar1 + -1;
      return;
    }
  }
  else if (*(long *)(lVar4 + -0x38) != *(long *)(param_1 + 0x22) ||
           *(long *)(lVar4 + -0x30) != *(long *)(param_1 + 0x24)) {
    FUN_00278dd8();
    return;
  }
  lVar5 = *(long *)(param_1 + 0x22);
  *(undefined8 *)(lVar4 + -0x30) = *(undefined8 *)(param_1 + 0x24);
  *(long *)(lVar4 + -0x38) = lVar5;
  return;
}



/* FUN_0027b1e4 at 0027b1e4 */

void FUN_0027b1e4(undefined4 param_1,long param_2,undefined8 *param_3,undefined8 *param_4,
                 ulong param_5)

{
  uint uVar1;
  uint uVar2;
  int iVar3;
  void *pvVar4;
  int iVar5;
  undefined8 uVar6;
  
  if ((param_5 & 0xff000000) != 0) {
    uVar6 = *param_3;
    iVar5 = *(int *)(param_2 + 0x78);
    if (iVar5 == *(int *)(param_2 + 0x7c)) {
      uVar1 = 8;
      if (iVar5 != 0) {
        uVar1 = iVar5 + iVar5 / 2;
      }
      if ((int)uVar1 <= (int)(iVar5 + 1U)) {
        uVar1 = iVar5 + 1U;
      }
      pvVar4 = (void *)FUN_00268fa0(-(ulong)(uVar1 >> 0x1f) & 0xfffffff800000000 | (ulong)uVar1 << 3
                                   );
      if (*(void **)(param_2 + 0x80) != (void *)0x0) {
        _memcpy(pvVar4,*(void **)(param_2 + 0x80),(long)*(int *)(param_2 + 0x78) << 3);
        FUN_002690a0(*(undefined8 *)(param_2 + 0x80));
      }
      *(void **)(param_2 + 0x80) = pvVar4;
      *(uint *)(param_2 + 0x7c) = uVar1;
      iVar5 = *(int *)(param_2 + 0x78);
    }
    else {
      pvVar4 = *(void **)(param_2 + 0x80);
    }
    *(ulong *)((long)pvVar4 + (long)iVar5 * 8) =
         CONCAT44((float)((ulong)uVar6 >> 0x20) + 0.5,(float)uVar6 + 0.5);
    iVar3 = *(int *)(param_2 + 0x78);
    iVar5 = iVar3 + 1;
    *(int *)(param_2 + 0x78) = iVar5;
    uVar6 = *param_4;
    if (iVar5 == *(int *)(param_2 + 0x7c)) {
      uVar1 = iVar3 + 2;
      uVar2 = 8;
      if (iVar5 != 0) {
        uVar2 = iVar5 + iVar5 / 2;
      }
      if ((int)uVar2 <= (int)uVar1) {
        uVar2 = uVar1;
      }
      pvVar4 = (void *)FUN_00268fa0(-(ulong)(uVar2 >> 0x1f) & 0xfffffff800000000 | (ulong)uVar2 << 3
                                   );
      if (*(void **)(param_2 + 0x80) != (void *)0x0) {
        _memcpy(pvVar4,*(void **)(param_2 + 0x80),(long)*(int *)(param_2 + 0x78) << 3);
        FUN_002690a0(*(undefined8 *)(param_2 + 0x80));
      }
      *(void **)(param_2 + 0x80) = pvVar4;
      *(uint *)(param_2 + 0x7c) = uVar2;
      iVar5 = *(int *)(param_2 + 0x78);
    }
    else {
      pvVar4 = *(void **)(param_2 + 0x80);
    }
    *(ulong *)((long)pvVar4 + (long)iVar5 * 8) =
         CONCAT44((float)((ulong)uVar6 >> 0x20) + 0.5,(float)uVar6 + 0.5);
    iVar5 = *(int *)(param_2 + 0x78) + 1;
    *(int *)(param_2 + 0x78) = iVar5;
    FUN_00279588(param_1,param_2,*(undefined8 *)(param_2 + 0x80),iVar5,param_5,0);
    *(undefined4 *)(param_2 + 0x78) = 0;
  }
  return;
}



/* FUN_0027b354 at 0027b354 */

void FUN_0027b354(undefined1 param_1 [16],undefined4 param_2,long param_3,undefined8 *param_4,
                 undefined8 *param_5,ulong param_6,undefined8 param_7)

{
  undefined8 uVar1;
  undefined8 uVar2;
  undefined8 local_40;
  undefined8 local_38;
  
  if ((param_6 & 0xff000000) != 0) {
    if ((*(byte *)(param_3 + 0x30) & 1) == 0) {
      local_38 = CONCAT44((float)((ulong)*param_4 >> 0x20) + 0.5,(float)*param_4 + 0.5);
      uVar1 = *param_5;
      uVar2 = 0xbefae148befae148;
    }
    else {
      local_38 = CONCAT44((float)((ulong)*param_4 >> 0x20) + 0.5,(float)*param_4 + 0.5);
      uVar1 = *param_5;
      uVar2 = 0xbf000000bf000000;
    }
    local_40 = CONCAT44((float)((ulong)uVar1 >> 0x20) + (float)((ulong)uVar2 >> 0x20),
                        (float)uVar1 + (float)uVar2);
    FUN_0027ae28(param_3,&local_38,&local_40,param_7);
    FUN_00279588(param_2,param_3,*(undefined8 *)(param_3 + 0x80),*(undefined4 *)(param_3 + 0x78),
                 param_6,1);
    *(undefined4 *)(param_3 + 0x78) = 0;
  }
  return;
}



/* FUN_0027b618 at 0027b618 */

void FUN_0027b618(undefined4 param_1,long param_2,undefined8 *param_3,undefined8 *param_4,
                 undefined8 *param_5,ulong param_6)

{
  uint uVar1;
  uint uVar2;
  int iVar3;
  void *pvVar4;
  int iVar5;
  
  if ((param_6 & 0xff000000) != 0) {
    iVar5 = *(int *)(param_2 + 0x78);
    if (iVar5 == *(int *)(param_2 + 0x7c)) {
      uVar1 = 8;
      if (iVar5 != 0) {
        uVar1 = iVar5 + iVar5 / 2;
      }
      if ((int)uVar1 <= (int)(iVar5 + 1U)) {
        uVar1 = iVar5 + 1U;
      }
      pvVar4 = (void *)FUN_00268fa0(-(ulong)(uVar1 >> 0x1f) & 0xfffffff800000000 | (ulong)uVar1 << 3
                                   );
      if (*(void **)(param_2 + 0x80) != (void *)0x0) {
        _memcpy(pvVar4,*(void **)(param_2 + 0x80),(long)*(int *)(param_2 + 0x78) << 3);
        FUN_002690a0(*(undefined8 *)(param_2 + 0x80));
      }
      *(void **)(param_2 + 0x80) = pvVar4;
      *(uint *)(param_2 + 0x7c) = uVar1;
      iVar5 = *(int *)(param_2 + 0x78);
    }
    else {
      pvVar4 = *(void **)(param_2 + 0x80);
    }
    *(undefined8 *)((long)pvVar4 + (long)iVar5 * 8) = *param_3;
    iVar3 = *(int *)(param_2 + 0x78);
    iVar5 = iVar3 + 1;
    *(int *)(param_2 + 0x78) = iVar5;
    if (iVar5 == *(int *)(param_2 + 0x7c)) {
      uVar1 = iVar3 + 2;
      uVar2 = 8;
      if (iVar5 != 0) {
        uVar2 = iVar5 + iVar5 / 2;
      }
      if ((int)uVar2 <= (int)uVar1) {
        uVar2 = uVar1;
      }
      pvVar4 = (void *)FUN_00268fa0(-(ulong)(uVar2 >> 0x1f) & 0xfffffff800000000 | (ulong)uVar2 << 3
                                   );
      if (*(void **)(param_2 + 0x80) != (void *)0x0) {
        _memcpy(pvVar4,*(void **)(param_2 + 0x80),(long)*(int *)(param_2 + 0x78) << 3);
        FUN_002690a0(*(undefined8 *)(param_2 + 0x80));
      }
      *(void **)(param_2 + 0x80) = pvVar4;
      *(uint *)(param_2 + 0x7c) = uVar2;
      iVar5 = *(int *)(param_2 + 0x78);
    }
    else {
      pvVar4 = *(void **)(param_2 + 0x80);
    }
    *(undefined8 *)((long)pvVar4 + (long)iVar5 * 8) = *param_4;
    iVar3 = *(int *)(param_2 + 0x78);
    iVar5 = iVar3 + 1;
    *(int *)(param_2 + 0x78) = iVar5;
    if (iVar5 == *(int *)(param_2 + 0x7c)) {
      uVar1 = iVar3 + 2;
      uVar2 = 8;
      if (iVar5 != 0) {
        uVar2 = iVar5 + iVar5 / 2;
      }
      if ((int)uVar2 <= (int)uVar1) {
        uVar2 = uVar1;
      }
      pvVar4 = (void *)FUN_00268fa0(-(ulong)(uVar2 >> 0x1f) & 0xfffffff800000000 | (ulong)uVar2 << 3
                                   );
      if (*(void **)(param_2 + 0x80) != (void *)0x0) {
        _memcpy(pvVar4,*(void **)(param_2 + 0x80),(long)*(int *)(param_2 + 0x78) << 3);
        FUN_002690a0(*(undefined8 *)(param_2 + 0x80));
      }
      *(void **)(param_2 + 0x80) = pvVar4;
      *(uint *)(param_2 + 0x7c) = uVar2;
      iVar5 = *(int *)(param_2 + 0x78);
    }
    else {
      pvVar4 = *(void **)(param_2 + 0x80);
    }
    *(undefined8 *)((long)pvVar4 + (long)iVar5 * 8) = *param_5;
    iVar5 = *(int *)(param_2 + 0x78) + 1;
    *(int *)(param_2 + 0x78) = iVar5;
    FUN_00279588(param_1,param_2,*(undefined8 *)(param_2 + 0x80),iVar5,param_6,1);
    *(undefined4 *)(param_2 + 0x78) = 0;
  }
  return;
}



/* FUN_0027b804 at 0027b804 */

void FUN_0027b804(long param_1,undefined8 *param_2,undefined8 *param_3,undefined8 *param_4,
                 undefined8 param_5)

{
  uint uVar1;
  uint uVar2;
  int iVar3;
  void *pvVar4;
  int iVar5;
  
  if ((uint)param_5 >> 0x18 != 0) {
    iVar5 = *(int *)(param_1 + 0x78);
    if (iVar5 == *(int *)(param_1 + 0x7c)) {
      uVar1 = 8;
      if (iVar5 != 0) {
        uVar1 = iVar5 + iVar5 / 2;
      }
      if ((int)uVar1 <= (int)(iVar5 + 1U)) {
        uVar1 = iVar5 + 1U;
      }
      pvVar4 = (void *)FUN_00268fa0(-(ulong)(uVar1 >> 0x1f) & 0xfffffff800000000 | (ulong)uVar1 << 3
                                   );
      if (*(void **)(param_1 + 0x80) != (void *)0x0) {
        _memcpy(pvVar4,*(void **)(param_1 + 0x80),(long)*(int *)(param_1 + 0x78) << 3);
        FUN_002690a0(*(undefined8 *)(param_1 + 0x80));
      }
      *(void **)(param_1 + 0x80) = pvVar4;
      *(uint *)(param_1 + 0x7c) = uVar1;
      iVar5 = *(int *)(param_1 + 0x78);
    }
    else {
      pvVar4 = *(void **)(param_1 + 0x80);
    }
    *(undefined8 *)((long)pvVar4 + (long)iVar5 * 8) = *param_2;
    iVar3 = *(int *)(param_1 + 0x78);
    iVar5 = iVar3 + 1;
    *(int *)(param_1 + 0x78) = iVar5;
    if (iVar5 == *(int *)(param_1 + 0x7c)) {
      uVar1 = iVar3 + 2;
      uVar2 = 8;
      if (iVar5 != 0) {
        uVar2 = iVar5 + iVar5 / 2;
      }
      if ((int)uVar2 <= (int)uVar1) {
        uVar2 = uVar1;
      }
      pvVar4 = (void *)FUN_00268fa0(-(ulong)(uVar2 >> 0x1f) & 0xfffffff800000000 | (ulong)uVar2 << 3
                                   );
      if (*(void **)(param_1 + 0x80) != (void *)0x0) {
        _memcpy(pvVar4,*(void **)(param_1 + 0x80),(long)*(int *)(param_1 + 0x78) << 3);
        FUN_002690a0(*(undefined8 *)(param_1 + 0x80));
      }
      *(void **)(param_1 + 0x80) = pvVar4;
      *(uint *)(param_1 + 0x7c) = uVar2;
      iVar5 = *(int *)(param_1 + 0x78);
    }
    else {
      pvVar4 = *(void **)(param_1 + 0x80);
    }
    *(undefined8 *)((long)pvVar4 + (long)iVar5 * 8) = *param_3;
    iVar3 = *(int *)(param_1 + 0x78);
    iVar5 = iVar3 + 1;
    *(int *)(param_1 + 0x78) = iVar5;
    if (iVar5 == *(int *)(param_1 + 0x7c)) {
      uVar1 = iVar3 + 2;
      uVar2 = 8;
      if (iVar5 != 0) {
        uVar2 = iVar5 + iVar5 / 2;
      }
      if ((int)uVar2 <= (int)uVar1) {
        uVar2 = uVar1;
      }
      pvVar4 = (void *)FUN_00268fa0(-(ulong)(uVar2 >> 0x1f) & 0xfffffff800000000 | (ulong)uVar2 << 3
                                   );
      if (*(void **)(param_1 + 0x80) != (void *)0x0) {
        _memcpy(pvVar4,*(void **)(param_1 + 0x80),(long)*(int *)(param_1 + 0x78) << 3);
        FUN_002690a0(*(undefined8 *)(param_1 + 0x80));
      }
      *(void **)(param_1 + 0x80) = pvVar4;
      *(uint *)(param_1 + 0x7c) = uVar2;
      iVar5 = *(int *)(param_1 + 0x78);
    }
    else {
      pvVar4 = *(void **)(param_1 + 0x80);
    }
    *(undefined8 *)((long)pvVar4 + (long)iVar5 * 8) = *param_4;
    iVar5 = *(int *)(param_1 + 0x78) + 1;
    *(int *)(param_1 + 0x78) = iVar5;
    FUN_00279dc8(param_1,*(undefined8 *)(param_1 + 0x80),iVar5,param_5);
    *(undefined4 *)(param_1 + 0x78) = 0;
  }
  return;
}



/* FUN_0027bad8 at 0027bad8 */

void FUN_0027bad8(float param_1,long param_2,undefined8 param_3,ulong param_4,uint param_5)

{
  uint uVar1;
  
  if (param_1 <= 0.0 || (param_4 & 0xff000000) == 0) {
    return;
  }
  if ((int)param_5 < 1) {
    uVar1 = FUN_00278ffc(param_1,param_2);
LAB_0027bb3c:
    if (uVar1 == 0xc) {
      FUN_0027a598(param_1,param_2,param_3,0,0xb);
      goto LAB_0027bb94;
    }
  }
  else {
    uVar1 = param_5;
    if (0x1ff < param_5) {
      uVar1 = 0x200;
    }
    if (2 < param_5) goto LAB_0027bb3c;
    uVar1 = 3;
  }
  FUN_0027a66c(param_1,0,(((float)uVar1 + -1.0) * DAT_0046d234) / (float)uVar1,param_2,param_3,
               uVar1 - 1);
LAB_0027bb94:
  FUN_00279dc8(param_2,*(undefined8 *)(param_2 + 0x80),*(undefined4 *)(param_2 + 0x78),param_4);
  *(undefined4 *)(param_2 + 0x78) = 0;
  return;
}



/* Recovered functions: 10 */
